// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/definition.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project       *Project               `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDefinition) Reset() {
	*x = ProcessDefinition{}
	mi := &file_entities_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDefinition) ProtoMessage() {}

func (x *ProcessDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_entities_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDefinition.ProtoReflect.Descriptor instead.
func (*ProcessDefinition) Descriptor() ([]byte, []int) {
	return file_entities_definition_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessDefinition) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProcessDefinition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProcessDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessDefinition) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_entities_definition_proto protoreflect.FileDescriptor

const file_entities_definition_proto_rawDesc = "" +
	"\n" +
	"\x19entities/definition.proto\x12\aprocess\x1a\x16entities/project.proto\"\x8f\x01\n" +
	"\x11ProcessDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\aproject\x18\x02 \x01(\v2\x10.process.ProjectR\aproject\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversionB\x91\x01\n" +
	"\vcom.processB\x0fDefinitionProtoP\x01Z5github.com/gsoultan/gobpm/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_definition_proto_rawDescOnce sync.Once
	file_entities_definition_proto_rawDescData []byte
)

func file_entities_definition_proto_rawDescGZIP() []byte {
	file_entities_definition_proto_rawDescOnce.Do(func() {
		file_entities_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_definition_proto_rawDesc), len(file_entities_definition_proto_rawDesc)))
	})
	return file_entities_definition_proto_rawDescData
}

var file_entities_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_definition_proto_goTypes = []any{
	(*ProcessDefinition)(nil), // 0: process.ProcessDefinition
	(*Project)(nil),           // 1: process.Project
}
var file_entities_definition_proto_depIdxs = []int32{
	1, // 0: process.ProcessDefinition.project:type_name -> process.Project
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entities_definition_proto_init() }
func file_entities_definition_proto_init() {
	if File_entities_definition_proto != nil {
		return
	}
	file_entities_project_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_definition_proto_rawDesc), len(file_entities_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_definition_proto_goTypes,
		DependencyIndexes: file_entities_definition_proto_depIdxs,
		MessageInfos:      file_entities_definition_proto_msgTypes,
	}.Build()
	File_entities_definition_proto = out.File
	file_entities_definition_proto_goTypes = nil
	file_entities_definition_proto_depIdxs = nil
}
