// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/external_task.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project       *Project               `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Instance      *ProcessInstance       `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	Node          *Node                  `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"`
	Retries       int32                  `protobuf:"varint,7,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalTask) Reset() {
	*x = ExternalTask{}
	mi := &file_entities_external_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalTask) ProtoMessage() {}

func (x *ExternalTask) ProtoReflect() protoreflect.Message {
	mi := &file_entities_external_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalTask.ProtoReflect.Descriptor instead.
func (*ExternalTask) Descriptor() ([]byte, []int) {
	return file_entities_external_task_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalTask) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ExternalTask) GetInstance() *ProcessInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ExternalTask) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExternalTask) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ExternalTask) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ExternalTask) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

var File_entities_external_task_proto protoreflect.FileDescriptor

const file_entities_external_task_proto_rawDesc = "" +
	"\n" +
	"\x1centities/external_task.proto\x12\aprocess\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13entities/node.proto\x1a\x16entities/project.proto\x1a\x1fentities/process_instance.proto\"\x8a\x02\n" +
	"\fExternalTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\aproject\x18\x02 \x01(\v2\x10.process.ProjectR\aproject\x124\n" +
	"\binstance\x18\x03 \x01(\v2\x18.process.ProcessInstanceR\binstance\x12!\n" +
	"\x04node\x18\x04 \x01(\v2\r.process.NodeR\x04node\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x125\n" +
	"\tvariables\x18\x06 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12\x18\n" +
	"\aretries\x18\a \x01(\x05R\aretriesB\x93\x01\n" +
	"\vcom.processB\x11ExternalTaskProtoP\x01Z5github.com/gsoultan/metis/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_external_task_proto_rawDescOnce sync.Once
	file_entities_external_task_proto_rawDescData []byte
)

func file_entities_external_task_proto_rawDescGZIP() []byte {
	file_entities_external_task_proto_rawDescOnce.Do(func() {
		file_entities_external_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_external_task_proto_rawDesc), len(file_entities_external_task_proto_rawDesc)))
	})
	return file_entities_external_task_proto_rawDescData
}

var file_entities_external_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_external_task_proto_goTypes = []any{
	(*ExternalTask)(nil),    // 0: process.ExternalTask
	(*Project)(nil),         // 1: process.Project
	(*ProcessInstance)(nil), // 2: process.ProcessInstance
	(*Node)(nil),            // 3: process.Node
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_entities_external_task_proto_depIdxs = []int32{
	1, // 0: process.ExternalTask.project:type_name -> process.Project
	2, // 1: process.ExternalTask.instance:type_name -> process.ProcessInstance
	3, // 2: process.ExternalTask.node:type_name -> process.Node
	4, // 3: process.ExternalTask.variables:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_entities_external_task_proto_init() }
func file_entities_external_task_proto_init() {
	if File_entities_external_task_proto != nil {
		return
	}
	file_entities_node_proto_init()
	file_entities_project_proto_init()
	file_entities_process_instance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_external_task_proto_rawDesc), len(file_entities_external_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_external_task_proto_goTypes,
		DependencyIndexes: file_entities_external_task_proto_depIdxs,
		MessageInfos:      file_entities_external_task_proto_msgTypes,
	}.Build()
	File_entities_external_task_proto = out.File
	file_entities_external_task_proto_goTypes = nil
	file_entities_external_task_proto_depIdxs = nil
}
