// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/flow.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Flow is one sequence flow: an arrow from one node to another, optionally
// guarded by a condition.
//
// The endpoints refer to nodes by id rather than embedding them. Embedding a
// whole Node here said the arrow owned a copy of the thing it points at, which
// is not what a flow is, and it made this file import node.proto — so a node
// could not in turn hold the flows of its sub-process without a cycle.
type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceRef     string                 `protobuf:"bytes,2,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	TargetRef     string                 `protobuf:"bytes,3,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Documentation string                 `protobuf:"bytes,5,opt,name=documentation,proto3" json:"documentation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_entities_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_entities_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_entities_flow_proto_rawDescGZIP(), []int{0}
}

func (x *Flow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flow) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Flow) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Flow) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Flow) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

var File_entities_flow_proto protoreflect.FileDescriptor

const file_entities_flow_proto_rawDesc = "" +
	"\n" +
	"\x13entities/flow.proto\x12\aprocess\"\x98\x01\n" +
	"\x04Flow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x02 \x01(\tR\tsourceRef\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x03 \x01(\tR\ttargetRef\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12$\n" +
	"\rdocumentation\x18\x05 \x01(\tR\rdocumentationB\x8b\x01\n" +
	"\vcom.processB\tFlowProtoP\x01Z5github.com/gsoultan/gobpm/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_flow_proto_rawDescOnce sync.Once
	file_entities_flow_proto_rawDescData []byte
)

func file_entities_flow_proto_rawDescGZIP() []byte {
	file_entities_flow_proto_rawDescOnce.Do(func() {
		file_entities_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_flow_proto_rawDesc), len(file_entities_flow_proto_rawDesc)))
	})
	return file_entities_flow_proto_rawDescData
}

var file_entities_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_flow_proto_goTypes = []any{
	(*Flow)(nil), // 0: process.Flow
}
var file_entities_flow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_flow_proto_init() }
func file_entities_flow_proto_init() {
	if File_entities_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_flow_proto_rawDesc), len(file_entities_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_flow_proto_goTypes,
		DependencyIndexes: file_entities_flow_proto_depIdxs,
		MessageInfos:      file_entities_flow_proto_msgTypes,
	}.Build()
	File_entities_flow_proto = out.File
	file_entities_flow_proto_goTypes = nil
	file_entities_flow_proto_depIdxs = nil
}
