// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/user.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrganization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrganization) Reset() {
	*x = UserOrganization{}
	mi := &file_entities_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrganization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrganization) ProtoMessage() {}

func (x *UserOrganization) ProtoReflect() protoreflect.Message {
	mi := &file_entities_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrganization.ProtoReflect.Descriptor instead.
func (*UserOrganization) Descriptor() ([]byte, []int) {
	return file_entities_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrganization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserOrganization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProject) Reset() {
	*x = UserProject{}
	mi := &file_entities_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProject) ProtoMessage() {}

func (x *UserProject) ProtoReflect() protoreflect.Message {
	mi := &file_entities_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProject.ProtoReflect.Descriptor instead.
func (*UserProject) Descriptor() ([]byte, []int) {
	return file_entities_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Organizations []*UserOrganization    `protobuf:"bytes,2,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Projects      []*UserProject         `protobuf:"bytes,8,rep,name=projects,proto3" json:"projects,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,9,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Organization  *Organization          `protobuf:"bytes,10,opt,name=organization,proto3" json:"organization,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_entities_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_entities_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_entities_user_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetOrganizations() []*UserOrganization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *User) GetProjects() []*UserProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_entities_user_proto protoreflect.FileDescriptor

const file_entities_user_proto_rawDesc = "" +
	"\n" +
	"\x13entities/user.proto\x12\aprocess\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bentities/organization.proto\"6\n" +
	"\x10UserOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\vUserProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x87\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\rorganizations\x18\x02 \x03(\v2\x19.process.UserOrganizationR\rorganizations\x120\n" +
	"\bprojects\x18\b \x03(\v2\x14.process.UserProjectR\bprojects\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12!\n" +
	"\fdisplay_name\x18\t \x01(\tR\vdisplayName\x129\n" +
	"\forganization\x18\n" +
	" \x01(\v2\x15.process.OrganizationR\forganization\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x8b\x01\n" +
	"\vcom.processB\tUserProtoP\x01Z5github.com/gsoultan/metis/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_user_proto_rawDescOnce sync.Once
	file_entities_user_proto_rawDescData []byte
)

func file_entities_user_proto_rawDescGZIP() []byte {
	file_entities_user_proto_rawDescOnce.Do(func() {
		file_entities_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_user_proto_rawDesc), len(file_entities_user_proto_rawDesc)))
	})
	return file_entities_user_proto_rawDescData
}

var file_entities_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_entities_user_proto_goTypes = []any{
	(*UserOrganization)(nil),      // 0: process.UserOrganization
	(*UserProject)(nil),           // 1: process.UserProject
	(*User)(nil),                  // 2: process.User
	(*Organization)(nil),          // 3: process.Organization
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_entities_user_proto_depIdxs = []int32{
	0, // 0: process.User.organizations:type_name -> process.UserOrganization
	1, // 1: process.User.projects:type_name -> process.UserProject
	3, // 2: process.User.organization:type_name -> process.Organization
	4, // 3: process.User.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_entities_user_proto_init() }
func file_entities_user_proto_init() {
	if File_entities_user_proto != nil {
		return
	}
	file_entities_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_user_proto_rawDesc), len(file_entities_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_user_proto_goTypes,
		DependencyIndexes: file_entities_user_proto_depIdxs,
		MessageInfos:      file_entities_user_proto_msgTypes,
	}.Build()
	File_entities_user_proto = out.File
	file_entities_user_proto_goTypes = nil
	file_entities_user_proto_depIdxs = nil
}
