// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/broadcast_signal.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,3,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastSignalRequest) Reset() {
	*x = BroadcastSignalRequest{}
	mi := &file_endpoints_broadcast_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSignalRequest) ProtoMessage() {}

func (x *BroadcastSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_broadcast_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSignalRequest.ProtoReflect.Descriptor instead.
func (*BroadcastSignalRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_broadcast_signal_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastSignalRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BroadcastSignalRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *BroadcastSignalRequest) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

type BroadcastSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastSignalResponse) Reset() {
	*x = BroadcastSignalResponse{}
	mi := &file_endpoints_broadcast_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSignalResponse) ProtoMessage() {}

func (x *BroadcastSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_broadcast_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSignalResponse.ProtoReflect.Descriptor instead.
func (*BroadcastSignalResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_broadcast_signal_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastSignalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_broadcast_signal_proto protoreflect.FileDescriptor

const file_endpoints_broadcast_signal_proto_rawDesc = "" +
	"\n" +
	" endpoints/broadcast_signal.proto\x12\aprocess\x1a\x1cgoogle/protobuf/struct.proto\"\x8f\x01\n" +
	"\x16BroadcastSignalRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x125\n" +
	"\tvariables\x18\x03 \x01(\v2\x17.google.protobuf.StructR\tvariables\"/\n" +
	"\x17BroadcastSignalResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x98\x01\n" +
	"\vcom.processB\x14BroadcastSignalProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_broadcast_signal_proto_rawDescOnce sync.Once
	file_endpoints_broadcast_signal_proto_rawDescData []byte
)

func file_endpoints_broadcast_signal_proto_rawDescGZIP() []byte {
	file_endpoints_broadcast_signal_proto_rawDescOnce.Do(func() {
		file_endpoints_broadcast_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_broadcast_signal_proto_rawDesc), len(file_endpoints_broadcast_signal_proto_rawDesc)))
	})
	return file_endpoints_broadcast_signal_proto_rawDescData
}

var file_endpoints_broadcast_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_broadcast_signal_proto_goTypes = []any{
	(*BroadcastSignalRequest)(nil),  // 0: process.BroadcastSignalRequest
	(*BroadcastSignalResponse)(nil), // 1: process.BroadcastSignalResponse
	(*structpb.Struct)(nil),         // 2: google.protobuf.Struct
}
var file_endpoints_broadcast_signal_proto_depIdxs = []int32{
	2, // 0: process.BroadcastSignalRequest.variables:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_broadcast_signal_proto_init() }
func file_endpoints_broadcast_signal_proto_init() {
	if File_endpoints_broadcast_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_broadcast_signal_proto_rawDesc), len(file_endpoints_broadcast_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_broadcast_signal_proto_goTypes,
		DependencyIndexes: file_endpoints_broadcast_signal_proto_depIdxs,
		MessageInfos:      file_endpoints_broadcast_signal_proto_msgTypes,
	}.Build()
	File_endpoints_broadcast_signal_proto = out.File
	file_endpoints_broadcast_signal_proto_goTypes = nil
	file_endpoints_broadcast_signal_proto_depIdxs = nil
}
