// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/create_definition.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []*entities.Node       `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Flows         []*entities.Flow       `protobuf:"bytes,5,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefinitionRequest) Reset() {
	*x = CreateDefinitionRequest{}
	mi := &file_endpoints_create_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefinitionRequest) ProtoMessage() {}

func (x *CreateDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_create_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_create_definition_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDefinitionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateDefinitionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDefinitionRequest) GetNodes() []*entities.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateDefinitionRequest) GetFlows() []*entities.Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type CreateDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefinitionResponse) Reset() {
	*x = CreateDefinitionResponse{}
	mi := &file_endpoints_create_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefinitionResponse) ProtoMessage() {}

func (x *CreateDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_create_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_create_definition_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDefinitionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_create_definition_proto protoreflect.FileDescriptor

const file_endpoints_create_definition_proto_rawDesc = "" +
	"\n" +
	"!endpoints/create_definition.proto\x12\aprocess\x1a\x13entities/node.proto\x1a\x13entities/flow.proto\"\xa8\x01\n" +
	"\x17CreateDefinitionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\x05nodes\x18\x04 \x03(\v2\r.process.NodeR\x05nodes\x12#\n" +
	"\x05flows\x18\x05 \x03(\v2\r.process.FlowR\x05flows\"@\n" +
	"\x18CreateDefinitionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\x99\x01\n" +
	"\vcom.processB\x15CreateDefinitionProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_create_definition_proto_rawDescOnce sync.Once
	file_endpoints_create_definition_proto_rawDescData []byte
)

func file_endpoints_create_definition_proto_rawDescGZIP() []byte {
	file_endpoints_create_definition_proto_rawDescOnce.Do(func() {
		file_endpoints_create_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_create_definition_proto_rawDesc), len(file_endpoints_create_definition_proto_rawDesc)))
	})
	return file_endpoints_create_definition_proto_rawDescData
}

var file_endpoints_create_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_create_definition_proto_goTypes = []any{
	(*CreateDefinitionRequest)(nil),  // 0: process.CreateDefinitionRequest
	(*CreateDefinitionResponse)(nil), // 1: process.CreateDefinitionResponse
	(*entities.Node)(nil),            // 2: process.Node
	(*entities.Flow)(nil),            // 3: process.Flow
}
var file_endpoints_create_definition_proto_depIdxs = []int32{
	2, // 0: process.CreateDefinitionRequest.nodes:type_name -> process.Node
	3, // 1: process.CreateDefinitionRequest.flows:type_name -> process.Flow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_endpoints_create_definition_proto_init() }
func file_endpoints_create_definition_proto_init() {
	if File_endpoints_create_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_create_definition_proto_rawDesc), len(file_endpoints_create_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_create_definition_proto_goTypes,
		DependencyIndexes: file_endpoints_create_definition_proto_depIdxs,
		MessageInfos:      file_endpoints_create_definition_proto_msgTypes,
	}.Build()
	File_endpoints_create_definition_proto = out.File
	file_endpoints_create_definition_proto_goTypes = nil
	file_endpoints_create_definition_proto_depIdxs = nil
}
