// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/delete_definition.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionRequest) Reset() {
	*x = DeleteDefinitionRequest{}
	mi := &file_endpoints_delete_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionRequest) ProtoMessage() {}

func (x *DeleteDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_delete_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_delete_definition_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionResponse) Reset() {
	*x = DeleteDefinitionResponse{}
	mi := &file_endpoints_delete_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionResponse) ProtoMessage() {}

func (x *DeleteDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_delete_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_delete_definition_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteDefinitionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_delete_definition_proto protoreflect.FileDescriptor

const file_endpoints_delete_definition_proto_rawDesc = "" +
	"\n" +
	"!endpoints/delete_definition.proto\x12\aprocess\")\n" +
	"\x17DeleteDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x18DeleteDefinitionResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x99\x01\n" +
	"\vcom.processB\x15DeleteDefinitionProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_delete_definition_proto_rawDescOnce sync.Once
	file_endpoints_delete_definition_proto_rawDescData []byte
)

func file_endpoints_delete_definition_proto_rawDescGZIP() []byte {
	file_endpoints_delete_definition_proto_rawDescOnce.Do(func() {
		file_endpoints_delete_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_delete_definition_proto_rawDesc), len(file_endpoints_delete_definition_proto_rawDesc)))
	})
	return file_endpoints_delete_definition_proto_rawDescData
}

var file_endpoints_delete_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_delete_definition_proto_goTypes = []any{
	(*DeleteDefinitionRequest)(nil),  // 0: process.DeleteDefinitionRequest
	(*DeleteDefinitionResponse)(nil), // 1: process.DeleteDefinitionResponse
}
var file_endpoints_delete_definition_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_delete_definition_proto_init() }
func file_endpoints_delete_definition_proto_init() {
	if File_endpoints_delete_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_delete_definition_proto_rawDesc), len(file_endpoints_delete_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_delete_definition_proto_goTypes,
		DependencyIndexes: file_endpoints_delete_definition_proto_depIdxs,
		MessageInfos:      file_endpoints_delete_definition_proto_msgTypes,
	}.Build()
	File_endpoints_delete_definition_proto = out.File
	file_endpoints_delete_definition_proto_goTypes = nil
	file_endpoints_delete_definition_proto_depIdxs = nil
}
