// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/fetch_and_lock_external_tasks.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchAndLockExternalTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxTasks       int32                  `protobuf:"varint,3,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	LockDurationMs int64                  `protobuf:"varint,4,opt,name=lock_duration_ms,json=lockDurationMs,proto3" json:"lock_duration_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchAndLockExternalTasksRequest) Reset() {
	*x = FetchAndLockExternalTasksRequest{}
	mi := &file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAndLockExternalTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAndLockExternalTasksRequest) ProtoMessage() {}

func (x *FetchAndLockExternalTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAndLockExternalTasksRequest.ProtoReflect.Descriptor instead.
func (*FetchAndLockExternalTasksRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_fetch_and_lock_external_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *FetchAndLockExternalTasksRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchAndLockExternalTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FetchAndLockExternalTasksRequest) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

func (x *FetchAndLockExternalTasksRequest) GetLockDurationMs() int64 {
	if x != nil {
		return x.LockDurationMs
	}
	return 0
}

type FetchAndLockExternalTasksResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tasks         []*entities.ExternalTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAndLockExternalTasksResponse) Reset() {
	*x = FetchAndLockExternalTasksResponse{}
	mi := &file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAndLockExternalTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAndLockExternalTasksResponse) ProtoMessage() {}

func (x *FetchAndLockExternalTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAndLockExternalTasksResponse.ProtoReflect.Descriptor instead.
func (*FetchAndLockExternalTasksResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_fetch_and_lock_external_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *FetchAndLockExternalTasksResponse) GetTasks() []*entities.ExternalTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *FetchAndLockExternalTasksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_fetch_and_lock_external_tasks_proto protoreflect.FileDescriptor

const file_endpoints_fetch_and_lock_external_tasks_proto_rawDesc = "" +
	"\n" +
	"-endpoints/fetch_and_lock_external_tasks.proto\x12\aprocess\x1a\x1centities/external_task.proto\"\x9c\x01\n" +
	" FetchAndLockExternalTasksRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tmax_tasks\x18\x03 \x01(\x05R\bmaxTasks\x12(\n" +
	"\x10lock_duration_ms\x18\x04 \x01(\x03R\x0elockDurationMs\"f\n" +
	"!FetchAndLockExternalTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.process.ExternalTaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\xa2\x01\n" +
	"\vcom.processB\x1eFetchAndLockExternalTasksProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_fetch_and_lock_external_tasks_proto_rawDescOnce sync.Once
	file_endpoints_fetch_and_lock_external_tasks_proto_rawDescData []byte
)

func file_endpoints_fetch_and_lock_external_tasks_proto_rawDescGZIP() []byte {
	file_endpoints_fetch_and_lock_external_tasks_proto_rawDescOnce.Do(func() {
		file_endpoints_fetch_and_lock_external_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_fetch_and_lock_external_tasks_proto_rawDesc), len(file_endpoints_fetch_and_lock_external_tasks_proto_rawDesc)))
	})
	return file_endpoints_fetch_and_lock_external_tasks_proto_rawDescData
}

var file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_fetch_and_lock_external_tasks_proto_goTypes = []any{
	(*FetchAndLockExternalTasksRequest)(nil),  // 0: process.FetchAndLockExternalTasksRequest
	(*FetchAndLockExternalTasksResponse)(nil), // 1: process.FetchAndLockExternalTasksResponse
	(*entities.ExternalTask)(nil),             // 2: process.ExternalTask
}
var file_endpoints_fetch_and_lock_external_tasks_proto_depIdxs = []int32{
	2, // 0: process.FetchAndLockExternalTasksResponse.tasks:type_name -> process.ExternalTask
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_fetch_and_lock_external_tasks_proto_init() }
func file_endpoints_fetch_and_lock_external_tasks_proto_init() {
	if File_endpoints_fetch_and_lock_external_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_fetch_and_lock_external_tasks_proto_rawDesc), len(file_endpoints_fetch_and_lock_external_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_fetch_and_lock_external_tasks_proto_goTypes,
		DependencyIndexes: file_endpoints_fetch_and_lock_external_tasks_proto_depIdxs,
		MessageInfos:      file_endpoints_fetch_and_lock_external_tasks_proto_msgTypes,
	}.Build()
	File_endpoints_fetch_and_lock_external_tasks_proto = out.File
	file_endpoints_fetch_and_lock_external_tasks_proto_goTypes = nil
	file_endpoints_fetch_and_lock_external_tasks_proto_depIdxs = nil
}
