// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/get_execution_path.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExecutionPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionPathRequest) Reset() {
	*x = GetExecutionPathRequest{}
	mi := &file_endpoints_get_execution_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionPathRequest) ProtoMessage() {}

func (x *GetExecutionPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_execution_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionPathRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionPathRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_get_execution_path_proto_rawDescGZIP(), []int{0}
}

func (x *GetExecutionPathRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetExecutionPathResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Nodes           []*entities.Node       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	NodeFrequencies map[string]int32       `protobuf:"bytes,3,rep,name=node_frequencies,json=nodeFrequencies,proto3" json:"node_frequencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExecutionPathResponse) Reset() {
	*x = GetExecutionPathResponse{}
	mi := &file_endpoints_get_execution_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionPathResponse) ProtoMessage() {}

func (x *GetExecutionPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_execution_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionPathResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionPathResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_get_execution_path_proto_rawDescGZIP(), []int{1}
}

func (x *GetExecutionPathResponse) GetNodes() []*entities.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetExecutionPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetExecutionPathResponse) GetNodeFrequencies() map[string]int32 {
	if x != nil {
		return x.NodeFrequencies
	}
	return nil
}

var File_endpoints_get_execution_path_proto protoreflect.FileDescriptor

const file_endpoints_get_execution_path_proto_rawDesc = "" +
	"\n" +
	"\"endpoints/get_execution_path.proto\x12\aprocess\x1a\x13entities/node.proto\":\n" +
	"\x17GetExecutionPathRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xfc\x01\n" +
	"\x18GetExecutionPathResponse\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.process.NodeR\x05nodes\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12a\n" +
	"\x10node_frequencies\x18\x03 \x03(\v26.process.GetExecutionPathResponse.NodeFrequenciesEntryR\x0fnodeFrequencies\x1aB\n" +
	"\x14NodeFrequenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x99\x01\n" +
	"\vcom.processB\x15GetExecutionPathProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_get_execution_path_proto_rawDescOnce sync.Once
	file_endpoints_get_execution_path_proto_rawDescData []byte
)

func file_endpoints_get_execution_path_proto_rawDescGZIP() []byte {
	file_endpoints_get_execution_path_proto_rawDescOnce.Do(func() {
		file_endpoints_get_execution_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_get_execution_path_proto_rawDesc), len(file_endpoints_get_execution_path_proto_rawDesc)))
	})
	return file_endpoints_get_execution_path_proto_rawDescData
}

var file_endpoints_get_execution_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_endpoints_get_execution_path_proto_goTypes = []any{
	(*GetExecutionPathRequest)(nil),  // 0: process.GetExecutionPathRequest
	(*GetExecutionPathResponse)(nil), // 1: process.GetExecutionPathResponse
	nil,                              // 2: process.GetExecutionPathResponse.NodeFrequenciesEntry
	(*entities.Node)(nil),            // 3: process.Node
}
var file_endpoints_get_execution_path_proto_depIdxs = []int32{
	3, // 0: process.GetExecutionPathResponse.nodes:type_name -> process.Node
	2, // 1: process.GetExecutionPathResponse.node_frequencies:type_name -> process.GetExecutionPathResponse.NodeFrequenciesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_endpoints_get_execution_path_proto_init() }
func file_endpoints_get_execution_path_proto_init() {
	if File_endpoints_get_execution_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_get_execution_path_proto_rawDesc), len(file_endpoints_get_execution_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_get_execution_path_proto_goTypes,
		DependencyIndexes: file_endpoints_get_execution_path_proto_depIdxs,
		MessageInfos:      file_endpoints_get_execution_path_proto_msgTypes,
	}.Build()
	File_endpoints_get_execution_path_proto = out.File
	file_endpoints_get_execution_path_proto_goTypes = nil
	file_endpoints_get_execution_path_proto_depIdxs = nil
}
