// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/get_project.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_endpoints_get_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_get_project_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *entities.Project      `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_endpoints_get_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_get_project_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectResponse) GetProject() *entities.Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GetProjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_get_project_proto protoreflect.FileDescriptor

const file_endpoints_get_project_proto_rawDesc = "" +
	"\n" +
	"\x1bendpoints/get_project.proto\x12\aprocess\x1a\x16entities/project.proto\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x12GetProjectResponse\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.process.ProjectR\aproject\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\x93\x01\n" +
	"\vcom.processB\x0fGetProjectProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_get_project_proto_rawDescOnce sync.Once
	file_endpoints_get_project_proto_rawDescData []byte
)

func file_endpoints_get_project_proto_rawDescGZIP() []byte {
	file_endpoints_get_project_proto_rawDescOnce.Do(func() {
		file_endpoints_get_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_get_project_proto_rawDesc), len(file_endpoints_get_project_proto_rawDesc)))
	})
	return file_endpoints_get_project_proto_rawDescData
}

var file_endpoints_get_project_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_get_project_proto_goTypes = []any{
	(*GetProjectRequest)(nil),  // 0: process.GetProjectRequest
	(*GetProjectResponse)(nil), // 1: process.GetProjectResponse
	(*entities.Project)(nil),   // 2: process.Project
}
var file_endpoints_get_project_proto_depIdxs = []int32{
	2, // 0: process.GetProjectResponse.project:type_name -> process.Project
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_get_project_proto_init() }
func file_endpoints_get_project_proto_init() {
	if File_endpoints_get_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_get_project_proto_rawDesc), len(file_endpoints_get_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_get_project_proto_goTypes,
		DependencyIndexes: file_endpoints_get_project_proto_depIdxs,
		MessageInfos:      file_endpoints_get_project_proto_msgTypes,
	}.Build()
	File_endpoints_get_project_proto = out.File
	file_endpoints_get_project_proto_goTypes = nil
	file_endpoints_get_project_proto_depIdxs = nil
}
