// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/get_process_statistics.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProcessStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessStatisticsRequest) Reset() {
	*x = GetProcessStatisticsRequest{}
	mi := &file_endpoints_get_process_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessStatisticsRequest) ProtoMessage() {}

func (x *GetProcessStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_process_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetProcessStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_get_process_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetProcessStatisticsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProcessStatisticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveInstances    int32                  `protobuf:"varint,1,opt,name=active_instances,json=activeInstances,proto3" json:"active_instances,omitempty"`
	CompletedInstances int32                  `protobuf:"varint,2,opt,name=completed_instances,json=completedInstances,proto3" json:"completed_instances,omitempty"`
	FailedInstances    int32                  `protobuf:"varint,3,opt,name=failed_instances,json=failedInstances,proto3" json:"failed_instances,omitempty"`
	TotalTasks         int32                  `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	PendingTasks       int32                  `protobuf:"varint,5,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProcessStatisticsResponse) Reset() {
	*x = GetProcessStatisticsResponse{}
	mi := &file_endpoints_get_process_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessStatisticsResponse) ProtoMessage() {}

func (x *GetProcessStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_get_process_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetProcessStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_get_process_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetProcessStatisticsResponse) GetActiveInstances() int32 {
	if x != nil {
		return x.ActiveInstances
	}
	return 0
}

func (x *GetProcessStatisticsResponse) GetCompletedInstances() int32 {
	if x != nil {
		return x.CompletedInstances
	}
	return 0
}

func (x *GetProcessStatisticsResponse) GetFailedInstances() int32 {
	if x != nil {
		return x.FailedInstances
	}
	return 0
}

func (x *GetProcessStatisticsResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *GetProcessStatisticsResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *GetProcessStatisticsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_get_process_statistics_proto protoreflect.FileDescriptor

const file_endpoints_get_process_statistics_proto_rawDesc = "" +
	"\n" +
	"&endpoints/get_process_statistics.proto\x12\aprocess\"<\n" +
	"\x1bGetProcessStatisticsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x81\x02\n" +
	"\x1cGetProcessStatisticsResponse\x12)\n" +
	"\x10active_instances\x18\x01 \x01(\x05R\x0factiveInstances\x12/\n" +
	"\x13completed_instances\x18\x02 \x01(\x05R\x12completedInstances\x12)\n" +
	"\x10failed_instances\x18\x03 \x01(\x05R\x0ffailedInstances\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12#\n" +
	"\rpending_tasks\x18\x05 \x01(\x05R\fpendingTasks\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB\x9d\x01\n" +
	"\vcom.processB\x19GetProcessStatisticsProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_get_process_statistics_proto_rawDescOnce sync.Once
	file_endpoints_get_process_statistics_proto_rawDescData []byte
)

func file_endpoints_get_process_statistics_proto_rawDescGZIP() []byte {
	file_endpoints_get_process_statistics_proto_rawDescOnce.Do(func() {
		file_endpoints_get_process_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_get_process_statistics_proto_rawDesc), len(file_endpoints_get_process_statistics_proto_rawDesc)))
	})
	return file_endpoints_get_process_statistics_proto_rawDescData
}

var file_endpoints_get_process_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_get_process_statistics_proto_goTypes = []any{
	(*GetProcessStatisticsRequest)(nil),  // 0: process.GetProcessStatisticsRequest
	(*GetProcessStatisticsResponse)(nil), // 1: process.GetProcessStatisticsResponse
}
var file_endpoints_get_process_statistics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_get_process_statistics_proto_init() }
func file_endpoints_get_process_statistics_proto_init() {
	if File_endpoints_get_process_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_get_process_statistics_proto_rawDesc), len(file_endpoints_get_process_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_get_process_statistics_proto_goTypes,
		DependencyIndexes: file_endpoints_get_process_statistics_proto_depIdxs,
		MessageInfos:      file_endpoints_get_process_statistics_proto_msgTypes,
	}.Build()
	File_endpoints_get_process_statistics_proto = out.File
	file_endpoints_get_process_statistics_proto_goTypes = nil
	file_endpoints_get_process_statistics_proto_depIdxs = nil
}
