// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/group.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListGroupsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_endpoints_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_group_proto_rawDescGZIP(), []int{0}
}

func (x *ListGroupsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*entities.Group      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_endpoints_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_group_proto_rawDescGZIP(), []int{1}
}

func (x *ListGroupsResponse) GetGroups() []*entities.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsRequest) Reset() {
	*x = ListUserGroupsRequest{}
	mi := &file_endpoints_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsRequest) ProtoMessage() {}

func (x *ListUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_group_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*entities.Group      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsResponse) Reset() {
	*x = ListUserGroupsResponse{}
	mi := &file_endpoints_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsResponse) ProtoMessage() {}

func (x *ListUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_group_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserGroupsResponse) GetGroups() []*entities.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_endpoints_group_proto protoreflect.FileDescriptor

const file_endpoints_group_proto_rawDesc = "" +
	"\n" +
	"\x15endpoints/group.proto\x12\aprocess\x1a\x14entities/group.proto\"<\n" +
	"\x11ListGroupsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"<\n" +
	"\x12ListGroupsResponse\x12&\n" +
	"\x06groups\x18\x01 \x03(\v2\x0e.process.GroupR\x06groups\"0\n" +
	"\x15ListUserGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x16ListUserGroupsResponse\x12&\n" +
	"\x06groups\x18\x01 \x03(\v2\x0e.process.GroupR\x06groupsB\x8e\x01\n" +
	"\vcom.processB\n" +
	"GroupProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_group_proto_rawDescOnce sync.Once
	file_endpoints_group_proto_rawDescData []byte
)

func file_endpoints_group_proto_rawDescGZIP() []byte {
	file_endpoints_group_proto_rawDescOnce.Do(func() {
		file_endpoints_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_group_proto_rawDesc), len(file_endpoints_group_proto_rawDesc)))
	})
	return file_endpoints_group_proto_rawDescData
}

var file_endpoints_group_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_endpoints_group_proto_goTypes = []any{
	(*ListGroupsRequest)(nil),      // 0: process.ListGroupsRequest
	(*ListGroupsResponse)(nil),     // 1: process.ListGroupsResponse
	(*ListUserGroupsRequest)(nil),  // 2: process.ListUserGroupsRequest
	(*ListUserGroupsResponse)(nil), // 3: process.ListUserGroupsResponse
	(*entities.Group)(nil),         // 4: process.Group
}
var file_endpoints_group_proto_depIdxs = []int32{
	4, // 0: process.ListGroupsResponse.groups:type_name -> process.Group
	4, // 1: process.ListUserGroupsResponse.groups:type_name -> process.Group
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_endpoints_group_proto_init() }
func file_endpoints_group_proto_init() {
	if File_endpoints_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_group_proto_rawDesc), len(file_endpoints_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_group_proto_goTypes,
		DependencyIndexes: file_endpoints_group_proto_depIdxs,
		MessageInfos:      file_endpoints_group_proto_msgTypes,
	}.Build()
	File_endpoints_group_proto = out.File
	file_endpoints_group_proto_goTypes = nil
	file_endpoints_group_proto_depIdxs = nil
}
