// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/handle_external_task_failure.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleExternalTaskFailureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorDetails   string                 `protobuf:"bytes,4,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	Retries        int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	RetryTimeoutMs int64                  `protobuf:"varint,6,opt,name=retry_timeout_ms,json=retryTimeoutMs,proto3" json:"retry_timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HandleExternalTaskFailureRequest) Reset() {
	*x = HandleExternalTaskFailureRequest{}
	mi := &file_endpoints_handle_external_task_failure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleExternalTaskFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleExternalTaskFailureRequest) ProtoMessage() {}

func (x *HandleExternalTaskFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_handle_external_task_failure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleExternalTaskFailureRequest.ProtoReflect.Descriptor instead.
func (*HandleExternalTaskFailureRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_handle_external_task_failure_proto_rawDescGZIP(), []int{0}
}

func (x *HandleExternalTaskFailureRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HandleExternalTaskFailureRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HandleExternalTaskFailureRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HandleExternalTaskFailureRequest) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

func (x *HandleExternalTaskFailureRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HandleExternalTaskFailureRequest) GetRetryTimeoutMs() int64 {
	if x != nil {
		return x.RetryTimeoutMs
	}
	return 0
}

type HandleExternalTaskFailureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleExternalTaskFailureResponse) Reset() {
	*x = HandleExternalTaskFailureResponse{}
	mi := &file_endpoints_handle_external_task_failure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleExternalTaskFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleExternalTaskFailureResponse) ProtoMessage() {}

func (x *HandleExternalTaskFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_handle_external_task_failure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleExternalTaskFailureResponse.ProtoReflect.Descriptor instead.
func (*HandleExternalTaskFailureResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_handle_external_task_failure_proto_rawDescGZIP(), []int{1}
}

func (x *HandleExternalTaskFailureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_handle_external_task_failure_proto protoreflect.FileDescriptor

const file_endpoints_handle_external_task_failure_proto_rawDesc = "" +
	"\n" +
	",endpoints/handle_external_task_failure.proto\x12\aprocess\"\xe6\x01\n" +
	" HandleExternalTaskFailureRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12#\n" +
	"\rerror_details\x18\x04 \x01(\tR\ferrorDetails\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12(\n" +
	"\x10retry_timeout_ms\x18\x06 \x01(\x03R\x0eretryTimeoutMs\"9\n" +
	"!HandleExternalTaskFailureResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\xa2\x01\n" +
	"\vcom.processB\x1eHandleExternalTaskFailureProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_handle_external_task_failure_proto_rawDescOnce sync.Once
	file_endpoints_handle_external_task_failure_proto_rawDescData []byte
)

func file_endpoints_handle_external_task_failure_proto_rawDescGZIP() []byte {
	file_endpoints_handle_external_task_failure_proto_rawDescOnce.Do(func() {
		file_endpoints_handle_external_task_failure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_handle_external_task_failure_proto_rawDesc), len(file_endpoints_handle_external_task_failure_proto_rawDesc)))
	})
	return file_endpoints_handle_external_task_failure_proto_rawDescData
}

var file_endpoints_handle_external_task_failure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_handle_external_task_failure_proto_goTypes = []any{
	(*HandleExternalTaskFailureRequest)(nil),  // 0: process.HandleExternalTaskFailureRequest
	(*HandleExternalTaskFailureResponse)(nil), // 1: process.HandleExternalTaskFailureResponse
}
var file_endpoints_handle_external_task_failure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_handle_external_task_failure_proto_init() }
func file_endpoints_handle_external_task_failure_proto_init() {
	if File_endpoints_handle_external_task_failure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_handle_external_task_failure_proto_rawDesc), len(file_endpoints_handle_external_task_failure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_handle_external_task_failure_proto_goTypes,
		DependencyIndexes: file_endpoints_handle_external_task_failure_proto_depIdxs,
		MessageInfos:      file_endpoints_handle_external_task_failure_proto_msgTypes,
	}.Build()
	File_endpoints_handle_external_task_failure_proto = out.File
	file_endpoints_handle_external_task_failure_proto_goTypes = nil
	file_endpoints_handle_external_task_failure_proto_depIdxs = nil
}
