// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_organizations.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_endpoints_list_organizations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_organizations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_organizations_proto_rawDescGZIP(), []int{0}
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Organizations []*entities.Organization `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Error         string                   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_endpoints_list_organizations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_organizations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_list_organizations_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*entities.Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_list_organizations_proto protoreflect.FileDescriptor

const file_endpoints_list_organizations_proto_rawDesc = "" +
	"\n" +
	"\"endpoints/list_organizations.proto\x12\aprocess\x1a\x1bentities/organization.proto\"\x1a\n" +
	"\x18ListOrganizationsRequest\"n\n" +
	"\x19ListOrganizationsResponse\x12;\n" +
	"\rorganizations\x18\x01 \x03(\v2\x15.process.OrganizationR\rorganizations\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\x9a\x01\n" +
	"\vcom.processB\x16ListOrganizationsProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_organizations_proto_rawDescOnce sync.Once
	file_endpoints_list_organizations_proto_rawDescData []byte
)

func file_endpoints_list_organizations_proto_rawDescGZIP() []byte {
	file_endpoints_list_organizations_proto_rawDescOnce.Do(func() {
		file_endpoints_list_organizations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_organizations_proto_rawDesc), len(file_endpoints_list_organizations_proto_rawDesc)))
	})
	return file_endpoints_list_organizations_proto_rawDescData
}

var file_endpoints_list_organizations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_list_organizations_proto_goTypes = []any{
	(*ListOrganizationsRequest)(nil),  // 0: process.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil), // 1: process.ListOrganizationsResponse
	(*entities.Organization)(nil),     // 2: process.Organization
}
var file_endpoints_list_organizations_proto_depIdxs = []int32{
	2, // 0: process.ListOrganizationsResponse.organizations:type_name -> process.Organization
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_list_organizations_proto_init() }
func file_endpoints_list_organizations_proto_init() {
	if File_endpoints_list_organizations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_organizations_proto_rawDesc), len(file_endpoints_list_organizations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_organizations_proto_goTypes,
		DependencyIndexes: file_endpoints_list_organizations_proto_depIdxs,
		MessageInfos:      file_endpoints_list_organizations_proto_msgTypes,
	}.Build()
	File_endpoints_list_organizations_proto = out.File
	file_endpoints_list_organizations_proto_goTypes = nil
	file_endpoints_list_organizations_proto_depIdxs = nil
}
