// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_tasks.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional; see PageRequest.
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_endpoints_list_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *ListTasksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListTasksRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Shared by ListTasks, ListTasksByAssignee and ListTasksByCandidates.
type ListTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tasks []*entities.Task       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Absent when the caller did not page, so an old client sees exactly the
	// response it saw before.
	Page          *PageInfo `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_endpoints_list_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_list_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksResponse) GetTasks() []*entities.Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListTasksResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_endpoints_list_tasks_proto protoreflect.FileDescriptor

const file_endpoints_list_tasks_proto_rawDesc = "" +
	"\n" +
	"\x1aendpoints/list_tasks.proto\x12\aprocess\x1a\x13entities/task.proto\x1a\x14endpoints/page.proto\"[\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.process.PageRequestR\x04page\"u\n" +
	"\x11ListTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.process.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x04page\x18\x03 \x01(\v2\x11.process.PageInfoR\x04pageB\x92\x01\n" +
	"\vcom.processB\x0eListTasksProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_tasks_proto_rawDescOnce sync.Once
	file_endpoints_list_tasks_proto_rawDescData []byte
)

func file_endpoints_list_tasks_proto_rawDescGZIP() []byte {
	file_endpoints_list_tasks_proto_rawDescOnce.Do(func() {
		file_endpoints_list_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_tasks_proto_rawDesc), len(file_endpoints_list_tasks_proto_rawDesc)))
	})
	return file_endpoints_list_tasks_proto_rawDescData
}

var file_endpoints_list_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_list_tasks_proto_goTypes = []any{
	(*ListTasksRequest)(nil),  // 0: process.ListTasksRequest
	(*ListTasksResponse)(nil), // 1: process.ListTasksResponse
	(*PageRequest)(nil),       // 2: process.PageRequest
	(*entities.Task)(nil),     // 3: process.Task
	(*PageInfo)(nil),          // 4: process.PageInfo
}
var file_endpoints_list_tasks_proto_depIdxs = []int32{
	2, // 0: process.ListTasksRequest.page:type_name -> process.PageRequest
	3, // 1: process.ListTasksResponse.tasks:type_name -> process.Task
	4, // 2: process.ListTasksResponse.page:type_name -> process.PageInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_endpoints_list_tasks_proto_init() }
func file_endpoints_list_tasks_proto_init() {
	if File_endpoints_list_tasks_proto != nil {
		return
	}
	file_endpoints_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_tasks_proto_rawDesc), len(file_endpoints_list_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_tasks_proto_goTypes,
		DependencyIndexes: file_endpoints_list_tasks_proto_depIdxs,
		MessageInfos:      file_endpoints_list_tasks_proto_msgTypes,
	}.Build()
	File_endpoints_list_tasks_proto = out.File
	file_endpoints_list_tasks_proto_goTypes = nil
	file_endpoints_list_tasks_proto_depIdxs = nil
}
