// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_instances.proto

package endpoints

import (
	entities "github.com/gsoultan/gobpm/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListInstancesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional; omitted means the first page at the server default.
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_endpoints_list_instances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_instances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_instances_proto_rawDescGZIP(), []int{0}
}

func (x *ListInstancesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListInstancesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListInstancesResponse struct {
	state     protoimpl.MessageState      `protogen:"open.v1"`
	Instances []*entities.ProcessInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Error     string                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Absent when the caller did not page.
	Page          *PageInfo `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_endpoints_list_instances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_instances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_list_instances_proto_rawDescGZIP(), []int{1}
}

func (x *ListInstancesResponse) GetInstances() []*entities.ProcessInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListInstancesResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_endpoints_list_instances_proto protoreflect.FileDescriptor

const file_endpoints_list_instances_proto_rawDesc = "" +
	"\n" +
	"\x1eendpoints/list_instances.proto\x12\aprocess\x1a\x1fentities/process_instance.proto\x1a\x14endpoints/page.proto\"_\n" +
	"\x14ListInstancesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.process.PageRequestR\x04page\"\x8c\x01\n" +
	"\x15ListInstancesResponse\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.process.ProcessInstanceR\tinstances\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x04page\x18\x03 \x01(\v2\x11.process.PageInfoR\x04pageB\x96\x01\n" +
	"\vcom.processB\x12ListInstancesProtoP\x01Z7github.com/gsoultan/gobpm/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_instances_proto_rawDescOnce sync.Once
	file_endpoints_list_instances_proto_rawDescData []byte
)

func file_endpoints_list_instances_proto_rawDescGZIP() []byte {
	file_endpoints_list_instances_proto_rawDescOnce.Do(func() {
		file_endpoints_list_instances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_instances_proto_rawDesc), len(file_endpoints_list_instances_proto_rawDesc)))
	})
	return file_endpoints_list_instances_proto_rawDescData
}

var file_endpoints_list_instances_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_list_instances_proto_goTypes = []any{
	(*ListInstancesRequest)(nil),     // 0: process.ListInstancesRequest
	(*ListInstancesResponse)(nil),    // 1: process.ListInstancesResponse
	(*PageRequest)(nil),              // 2: process.PageRequest
	(*entities.ProcessInstance)(nil), // 3: process.ProcessInstance
	(*PageInfo)(nil),                 // 4: process.PageInfo
}
var file_endpoints_list_instances_proto_depIdxs = []int32{
	2, // 0: process.ListInstancesRequest.page:type_name -> process.PageRequest
	3, // 1: process.ListInstancesResponse.instances:type_name -> process.ProcessInstance
	4, // 2: process.ListInstancesResponse.page:type_name -> process.PageInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_endpoints_list_instances_proto_init() }
func file_endpoints_list_instances_proto_init() {
	if File_endpoints_list_instances_proto != nil {
		return
	}
	file_endpoints_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_instances_proto_rawDesc), len(file_endpoints_list_instances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_instances_proto_goTypes,
		DependencyIndexes: file_endpoints_list_instances_proto_depIdxs,
		MessageInfos:      file_endpoints_list_instances_proto_msgTypes,
	}.Build()
	File_endpoints_list_instances_proto = out.File
	file_endpoints_list_instances_proto_goTypes = nil
	file_endpoints_list_instances_proto_depIdxs = nil
}
