// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_projects.proto

package endpoints

import (
	entities "github.com/gsoultan/metis/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProjectsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_endpoints_list_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_projects_proto_rawDescGZIP(), []int{0}
}

func (x *ListProjectsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*entities.Project    `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_endpoints_list_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_list_projects_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*entities.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_list_projects_proto protoreflect.FileDescriptor

const file_endpoints_list_projects_proto_rawDesc = "" +
	"\n" +
	"\x1dendpoints/list_projects.proto\x12\aprocess\x1a\x16entities/project.proto\">\n" +
	"\x13ListProjectsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"Z\n" +
	"\x14ListProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.process.ProjectR\bprojects\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\x95\x01\n" +
	"\vcom.processB\x11ListProjectsProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_projects_proto_rawDescOnce sync.Once
	file_endpoints_list_projects_proto_rawDescData []byte
)

func file_endpoints_list_projects_proto_rawDescGZIP() []byte {
	file_endpoints_list_projects_proto_rawDescOnce.Do(func() {
		file_endpoints_list_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_projects_proto_rawDesc), len(file_endpoints_list_projects_proto_rawDesc)))
	})
	return file_endpoints_list_projects_proto_rawDescData
}

var file_endpoints_list_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_list_projects_proto_goTypes = []any{
	(*ListProjectsRequest)(nil),  // 0: process.ListProjectsRequest
	(*ListProjectsResponse)(nil), // 1: process.ListProjectsResponse
	(*entities.Project)(nil),     // 2: process.Project
}
var file_endpoints_list_projects_proto_depIdxs = []int32{
	2, // 0: process.ListProjectsResponse.projects:type_name -> process.Project
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_list_projects_proto_init() }
func file_endpoints_list_projects_proto_init() {
	if File_endpoints_list_projects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_projects_proto_rawDesc), len(file_endpoints_list_projects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_projects_proto_goTypes,
		DependencyIndexes: file_endpoints_list_projects_proto_depIdxs,
		MessageInfos:      file_endpoints_list_projects_proto_msgTypes,
	}.Build()
	File_endpoints_list_projects_proto = out.File
	file_endpoints_list_projects_proto_goTypes = nil
	file_endpoints_list_projects_proto_depIdxs = nil
}
