// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/unclaim_task.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnclaimTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnclaimTaskRequest) Reset() {
	*x = UnclaimTaskRequest{}
	mi := &file_endpoints_unclaim_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnclaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnclaimTaskRequest) ProtoMessage() {}

func (x *UnclaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_unclaim_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnclaimTaskRequest.ProtoReflect.Descriptor instead.
func (*UnclaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_unclaim_task_proto_rawDescGZIP(), []int{0}
}

func (x *UnclaimTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnclaimTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnclaimTaskResponse) Reset() {
	*x = UnclaimTaskResponse{}
	mi := &file_endpoints_unclaim_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnclaimTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnclaimTaskResponse) ProtoMessage() {}

func (x *UnclaimTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_unclaim_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnclaimTaskResponse.ProtoReflect.Descriptor instead.
func (*UnclaimTaskResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_unclaim_task_proto_rawDescGZIP(), []int{1}
}

func (x *UnclaimTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_unclaim_task_proto protoreflect.FileDescriptor

const file_endpoints_unclaim_task_proto_rawDesc = "" +
	"\n" +
	"\x1cendpoints/unclaim_task.proto\x12\aprocess\"$\n" +
	"\x12UnclaimTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x13UnclaimTaskResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x94\x01\n" +
	"\vcom.processB\x10UnclaimTaskProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_unclaim_task_proto_rawDescOnce sync.Once
	file_endpoints_unclaim_task_proto_rawDescData []byte
)

func file_endpoints_unclaim_task_proto_rawDescGZIP() []byte {
	file_endpoints_unclaim_task_proto_rawDescOnce.Do(func() {
		file_endpoints_unclaim_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_unclaim_task_proto_rawDesc), len(file_endpoints_unclaim_task_proto_rawDesc)))
	})
	return file_endpoints_unclaim_task_proto_rawDescData
}

var file_endpoints_unclaim_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_unclaim_task_proto_goTypes = []any{
	(*UnclaimTaskRequest)(nil),  // 0: process.UnclaimTaskRequest
	(*UnclaimTaskResponse)(nil), // 1: process.UnclaimTaskResponse
}
var file_endpoints_unclaim_task_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_unclaim_task_proto_init() }
func file_endpoints_unclaim_task_proto_init() {
	if File_endpoints_unclaim_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_unclaim_task_proto_rawDesc), len(file_endpoints_unclaim_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_unclaim_task_proto_goTypes,
		DependencyIndexes: file_endpoints_unclaim_task_proto_depIdxs,
		MessageInfos:      file_endpoints_unclaim_task_proto_msgTypes,
	}.Build()
	File_endpoints_unclaim_task_proto = out.File
	file_endpoints_unclaim_task_proto_goTypes = nil
	file_endpoints_unclaim_task_proto_depIdxs = nil
}
