// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/update_organization.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_endpoints_update_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_update_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_update_organization_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_endpoints_update_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_update_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_update_organization_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOrganizationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_update_organization_proto protoreflect.FileDescriptor

const file_endpoints_update_organization_proto_rawDesc = "" +
	"\n" +
	"#endpoints/update_organization.proto\x12\aprocess\"a\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x1aUpdateOrganizationResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x9b\x01\n" +
	"\vcom.processB\x17UpdateOrganizationProtoP\x01Z7github.com/gsoultan/metis/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_update_organization_proto_rawDescOnce sync.Once
	file_endpoints_update_organization_proto_rawDescData []byte
)

func file_endpoints_update_organization_proto_rawDescGZIP() []byte {
	file_endpoints_update_organization_proto_rawDescOnce.Do(func() {
		file_endpoints_update_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_update_organization_proto_rawDesc), len(file_endpoints_update_organization_proto_rawDesc)))
	})
	return file_endpoints_update_organization_proto_rawDescData
}

var file_endpoints_update_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_update_organization_proto_goTypes = []any{
	(*UpdateOrganizationRequest)(nil),  // 0: process.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil), // 1: process.UpdateOrganizationResponse
}
var file_endpoints_update_organization_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_update_organization_proto_init() }
func file_endpoints_update_organization_proto_init() {
	if File_endpoints_update_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_update_organization_proto_rawDesc), len(file_endpoints_update_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_update_organization_proto_goTypes,
		DependencyIndexes: file_endpoints_update_organization_proto_depIdxs,
		MessageInfos:      file_endpoints_update_organization_proto_msgTypes,
	}.Build()
	File_endpoints_update_organization_proto = out.File
	file_endpoints_update_organization_proto_goTypes = nil
	file_endpoints_update_organization_proto_depIdxs = nil
}
