package drift_test

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/gsoultan/metis/server/domains/entities"
	"github.com/gsoultan/metis/server/repositories"
	"github.com/gsoultan/metis/server/repositories/models"
	"github.com/gsoultan/metis/server/repositories/store/job"
	"github.com/gsoultan/metis/tests/testutils"
)

// The query builders under server/repositories/store are generated by storm
// and checked in, and they are compiled against the storm runtime go.mod pins.
// #66 moved the runtime from v0.10.0 to v0.15.0 without regenerating them, so
// the process ran v0.10.0 builders — among them one that bound a null test's
// absent value to the parameter after it, which is how a query asking for
// "no lease or an expired one" matched unleased rows only.
func TestTheGeneratedStoreComesFromTheStormTheModuleBuildsAgainst(t *testing.T) {
	// Rooted at the repository, so nothing here can read outside it.
	repo := os.DirFS(filepath.Join("..", ".."))
	goMod, err := fs.ReadFile(repo, "go.mod")
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	pinned := regexp.MustCompile(`github\.com/gsoultan/storm (v[0-9]+\.[0-9]+\.[0-9]+)`).FindSubmatch(goMod)
	if pinned == nil {
		t.Fatal("go.mod does not pin github.com/gsoultan/storm")
	}
	want := "// Code generated by storm " + string(pinned[1]) + "."

	generated, err := fs.Glob(repo, "server/repositories/store/*/*.gen.go")
	if err != nil || len(generated) == 0 {
		t.Fatalf("find the generated store: %d files, %v", len(generated), err)
	}
	var stale []string
	for _, path := range generated {
		content, err := fs.ReadFile(repo, path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if !strings.HasPrefix(string(content), want) {
			firstLine, _, _ := strings.Cut(string(content), "\n")
			stale = append(stale, filepath.Base(path)+": "+firstLine)
		}
	}
	if len(stale) > 0 {
		t.Fatalf("%d generated files were not produced by storm %s — run `make generate`:\n%s",
			len(stale), pinned[1], strings.Join(stale, "\n"))
	}
}

// The builder bug itself, against a real database: a row whose lease expired
// must match "no lease, or an expired one", whichever way round it is asked.
func TestANullTestInsideAnyKeepsThePredicateAfterIt(t *testing.T) {
	_, conn := testutils.SetupTestStore(t)
	repo := repositories.NewRepository(conn)
	ctx := entities.WithSystemContext(t.Context())

	expired := time.Now().Add(-time.Minute)
	if _, err := repo.Job().Create(ctx, models.JobModel{
		Base: models.Base{ID: models.UUID(uuid.New())}, Type: "timer", Status: models.JobRunning,
		NextRunAt: expired, LockExpires: &expired, LockedBy: "a worker that died",
	}); err != nil {
		t.Fatalf("seed a job: %v", err)
	}

	ex, err := conn.Executor(ctx)
	if err != nil {
		t.Fatalf("executor: %v", err)
	}
	now := time.Now().UTC()
	for name, query := range map[string]job.Query{
		"null test first":  job.New().Any(job.LockExpires.IsNull(), job.LockExpires.Lt(now)),
		"null test second": job.New().Any(job.LockExpires.Lt(now), job.LockExpires.IsNull()),
	} {
		rows, err := query.All(ctx, ex, nil)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if len(rows) != 1 {
			t.Errorf("%s: matched %d rows, want the one whose lease expired", name, len(rows))
		}
	}
}
