// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/definition.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DefinitionServiceName is the fully-qualified name of the DefinitionService service.
	DefinitionServiceName = "process.DefinitionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DefinitionServiceCreateDefinitionProcedure is the fully-qualified name of the DefinitionService's
	// CreateDefinition RPC.
	DefinitionServiceCreateDefinitionProcedure = "/process.DefinitionService/CreateDefinition"
	// DefinitionServiceListDefinitionsProcedure is the fully-qualified name of the DefinitionService's
	// ListDefinitions RPC.
	DefinitionServiceListDefinitionsProcedure = "/process.DefinitionService/ListDefinitions"
	// DefinitionServiceGetDefinitionProcedure is the fully-qualified name of the DefinitionService's
	// GetDefinition RPC.
	DefinitionServiceGetDefinitionProcedure = "/process.DefinitionService/GetDefinition"
	// DefinitionServiceDeleteDefinitionProcedure is the fully-qualified name of the DefinitionService's
	// DeleteDefinition RPC.
	DefinitionServiceDeleteDefinitionProcedure = "/process.DefinitionService/DeleteDefinition"
)

// DefinitionServiceClient is a client for the process.DefinitionService service.
type DefinitionServiceClient interface {
	CreateDefinition(context.Context, *connect.Request[endpoints.CreateDefinitionRequest]) (*connect.Response[endpoints.CreateDefinitionResponse], error)
	ListDefinitions(context.Context, *connect.Request[endpoints.ListDefinitionsRequest]) (*connect.Response[endpoints.ListDefinitionsResponse], error)
	GetDefinition(context.Context, *connect.Request[endpoints.GetDefinitionRequest]) (*connect.Response[endpoints.GetDefinitionResponse], error)
	DeleteDefinition(context.Context, *connect.Request[endpoints.DeleteDefinitionRequest]) (*connect.Response[endpoints.DeleteDefinitionResponse], error)
}

// NewDefinitionServiceClient constructs a client for the process.DefinitionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDefinitionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DefinitionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	definitionServiceMethods := services.File_services_definition_proto.Services().ByName("DefinitionService").Methods()
	return &definitionServiceClient{
		createDefinition: connect.NewClient[endpoints.CreateDefinitionRequest, endpoints.CreateDefinitionResponse](
			httpClient,
			baseURL+DefinitionServiceCreateDefinitionProcedure,
			connect.WithSchema(definitionServiceMethods.ByName("CreateDefinition")),
			connect.WithClientOptions(opts...),
		),
		listDefinitions: connect.NewClient[endpoints.ListDefinitionsRequest, endpoints.ListDefinitionsResponse](
			httpClient,
			baseURL+DefinitionServiceListDefinitionsProcedure,
			connect.WithSchema(definitionServiceMethods.ByName("ListDefinitions")),
			connect.WithClientOptions(opts...),
		),
		getDefinition: connect.NewClient[endpoints.GetDefinitionRequest, endpoints.GetDefinitionResponse](
			httpClient,
			baseURL+DefinitionServiceGetDefinitionProcedure,
			connect.WithSchema(definitionServiceMethods.ByName("GetDefinition")),
			connect.WithClientOptions(opts...),
		),
		deleteDefinition: connect.NewClient[endpoints.DeleteDefinitionRequest, endpoints.DeleteDefinitionResponse](
			httpClient,
			baseURL+DefinitionServiceDeleteDefinitionProcedure,
			connect.WithSchema(definitionServiceMethods.ByName("DeleteDefinition")),
			connect.WithClientOptions(opts...),
		),
	}
}

// definitionServiceClient implements DefinitionServiceClient.
type definitionServiceClient struct {
	createDefinition *connect.Client[endpoints.CreateDefinitionRequest, endpoints.CreateDefinitionResponse]
	listDefinitions  *connect.Client[endpoints.ListDefinitionsRequest, endpoints.ListDefinitionsResponse]
	getDefinition    *connect.Client[endpoints.GetDefinitionRequest, endpoints.GetDefinitionResponse]
	deleteDefinition *connect.Client[endpoints.DeleteDefinitionRequest, endpoints.DeleteDefinitionResponse]
}

// CreateDefinition calls process.DefinitionService.CreateDefinition.
func (c *definitionServiceClient) CreateDefinition(ctx context.Context, req *connect.Request[endpoints.CreateDefinitionRequest]) (*connect.Response[endpoints.CreateDefinitionResponse], error) {
	return c.createDefinition.CallUnary(ctx, req)
}

// ListDefinitions calls process.DefinitionService.ListDefinitions.
func (c *definitionServiceClient) ListDefinitions(ctx context.Context, req *connect.Request[endpoints.ListDefinitionsRequest]) (*connect.Response[endpoints.ListDefinitionsResponse], error) {
	return c.listDefinitions.CallUnary(ctx, req)
}

// GetDefinition calls process.DefinitionService.GetDefinition.
func (c *definitionServiceClient) GetDefinition(ctx context.Context, req *connect.Request[endpoints.GetDefinitionRequest]) (*connect.Response[endpoints.GetDefinitionResponse], error) {
	return c.getDefinition.CallUnary(ctx, req)
}

// DeleteDefinition calls process.DefinitionService.DeleteDefinition.
func (c *definitionServiceClient) DeleteDefinition(ctx context.Context, req *connect.Request[endpoints.DeleteDefinitionRequest]) (*connect.Response[endpoints.DeleteDefinitionResponse], error) {
	return c.deleteDefinition.CallUnary(ctx, req)
}

// DefinitionServiceHandler is an implementation of the process.DefinitionService service.
type DefinitionServiceHandler interface {
	CreateDefinition(context.Context, *connect.Request[endpoints.CreateDefinitionRequest]) (*connect.Response[endpoints.CreateDefinitionResponse], error)
	ListDefinitions(context.Context, *connect.Request[endpoints.ListDefinitionsRequest]) (*connect.Response[endpoints.ListDefinitionsResponse], error)
	GetDefinition(context.Context, *connect.Request[endpoints.GetDefinitionRequest]) (*connect.Response[endpoints.GetDefinitionResponse], error)
	DeleteDefinition(context.Context, *connect.Request[endpoints.DeleteDefinitionRequest]) (*connect.Response[endpoints.DeleteDefinitionResponse], error)
}

// NewDefinitionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDefinitionServiceHandler(svc DefinitionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	definitionServiceMethods := services.File_services_definition_proto.Services().ByName("DefinitionService").Methods()
	definitionServiceCreateDefinitionHandler := connect.NewUnaryHandler(
		DefinitionServiceCreateDefinitionProcedure,
		svc.CreateDefinition,
		connect.WithSchema(definitionServiceMethods.ByName("CreateDefinition")),
		connect.WithHandlerOptions(opts...),
	)
	definitionServiceListDefinitionsHandler := connect.NewUnaryHandler(
		DefinitionServiceListDefinitionsProcedure,
		svc.ListDefinitions,
		connect.WithSchema(definitionServiceMethods.ByName("ListDefinitions")),
		connect.WithHandlerOptions(opts...),
	)
	definitionServiceGetDefinitionHandler := connect.NewUnaryHandler(
		DefinitionServiceGetDefinitionProcedure,
		svc.GetDefinition,
		connect.WithSchema(definitionServiceMethods.ByName("GetDefinition")),
		connect.WithHandlerOptions(opts...),
	)
	definitionServiceDeleteDefinitionHandler := connect.NewUnaryHandler(
		DefinitionServiceDeleteDefinitionProcedure,
		svc.DeleteDefinition,
		connect.WithSchema(definitionServiceMethods.ByName("DeleteDefinition")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.DefinitionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DefinitionServiceCreateDefinitionProcedure:
			definitionServiceCreateDefinitionHandler.ServeHTTP(w, r)
		case DefinitionServiceListDefinitionsProcedure:
			definitionServiceListDefinitionsHandler.ServeHTTP(w, r)
		case DefinitionServiceGetDefinitionProcedure:
			definitionServiceGetDefinitionHandler.ServeHTTP(w, r)
		case DefinitionServiceDeleteDefinitionProcedure:
			definitionServiceDeleteDefinitionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDefinitionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDefinitionServiceHandler struct{}

func (UnimplementedDefinitionServiceHandler) CreateDefinition(context.Context, *connect.Request[endpoints.CreateDefinitionRequest]) (*connect.Response[endpoints.CreateDefinitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.DefinitionService.CreateDefinition is not implemented"))
}

func (UnimplementedDefinitionServiceHandler) ListDefinitions(context.Context, *connect.Request[endpoints.ListDefinitionsRequest]) (*connect.Response[endpoints.ListDefinitionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.DefinitionService.ListDefinitions is not implemented"))
}

func (UnimplementedDefinitionServiceHandler) GetDefinition(context.Context, *connect.Request[endpoints.GetDefinitionRequest]) (*connect.Response[endpoints.GetDefinitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.DefinitionService.GetDefinition is not implemented"))
}

func (UnimplementedDefinitionServiceHandler) DeleteDefinition(context.Context, *connect.Request[endpoints.DeleteDefinitionRequest]) (*connect.Response[endpoints.DeleteDefinitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.DefinitionService.DeleteDefinition is not implemented"))
}
