// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/external_task.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExternalTaskServiceName is the fully-qualified name of the ExternalTaskService service.
	ExternalTaskServiceName = "process.ExternalTaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExternalTaskServiceFetchAndLockExternalTasksProcedure is the fully-qualified name of the
	// ExternalTaskService's FetchAndLockExternalTasks RPC.
	ExternalTaskServiceFetchAndLockExternalTasksProcedure = "/process.ExternalTaskService/FetchAndLockExternalTasks"
	// ExternalTaskServiceCompleteExternalTaskProcedure is the fully-qualified name of the
	// ExternalTaskService's CompleteExternalTask RPC.
	ExternalTaskServiceCompleteExternalTaskProcedure = "/process.ExternalTaskService/CompleteExternalTask"
	// ExternalTaskServiceHandleExternalTaskFailureProcedure is the fully-qualified name of the
	// ExternalTaskService's HandleExternalTaskFailure RPC.
	ExternalTaskServiceHandleExternalTaskFailureProcedure = "/process.ExternalTaskService/HandleExternalTaskFailure"
)

// ExternalTaskServiceClient is a client for the process.ExternalTaskService service.
type ExternalTaskServiceClient interface {
	FetchAndLockExternalTasks(context.Context, *connect.Request[endpoints.FetchAndLockExternalTasksRequest]) (*connect.Response[endpoints.FetchAndLockExternalTasksResponse], error)
	CompleteExternalTask(context.Context, *connect.Request[endpoints.CompleteExternalTaskRequest]) (*connect.Response[endpoints.CompleteExternalTaskResponse], error)
	HandleExternalTaskFailure(context.Context, *connect.Request[endpoints.HandleExternalTaskFailureRequest]) (*connect.Response[endpoints.HandleExternalTaskFailureResponse], error)
}

// NewExternalTaskServiceClient constructs a client for the process.ExternalTaskService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExternalTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExternalTaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	externalTaskServiceMethods := services.File_services_external_task_proto.Services().ByName("ExternalTaskService").Methods()
	return &externalTaskServiceClient{
		fetchAndLockExternalTasks: connect.NewClient[endpoints.FetchAndLockExternalTasksRequest, endpoints.FetchAndLockExternalTasksResponse](
			httpClient,
			baseURL+ExternalTaskServiceFetchAndLockExternalTasksProcedure,
			connect.WithSchema(externalTaskServiceMethods.ByName("FetchAndLockExternalTasks")),
			connect.WithClientOptions(opts...),
		),
		completeExternalTask: connect.NewClient[endpoints.CompleteExternalTaskRequest, endpoints.CompleteExternalTaskResponse](
			httpClient,
			baseURL+ExternalTaskServiceCompleteExternalTaskProcedure,
			connect.WithSchema(externalTaskServiceMethods.ByName("CompleteExternalTask")),
			connect.WithClientOptions(opts...),
		),
		handleExternalTaskFailure: connect.NewClient[endpoints.HandleExternalTaskFailureRequest, endpoints.HandleExternalTaskFailureResponse](
			httpClient,
			baseURL+ExternalTaskServiceHandleExternalTaskFailureProcedure,
			connect.WithSchema(externalTaskServiceMethods.ByName("HandleExternalTaskFailure")),
			connect.WithClientOptions(opts...),
		),
	}
}

// externalTaskServiceClient implements ExternalTaskServiceClient.
type externalTaskServiceClient struct {
	fetchAndLockExternalTasks *connect.Client[endpoints.FetchAndLockExternalTasksRequest, endpoints.FetchAndLockExternalTasksResponse]
	completeExternalTask      *connect.Client[endpoints.CompleteExternalTaskRequest, endpoints.CompleteExternalTaskResponse]
	handleExternalTaskFailure *connect.Client[endpoints.HandleExternalTaskFailureRequest, endpoints.HandleExternalTaskFailureResponse]
}

// FetchAndLockExternalTasks calls process.ExternalTaskService.FetchAndLockExternalTasks.
func (c *externalTaskServiceClient) FetchAndLockExternalTasks(ctx context.Context, req *connect.Request[endpoints.FetchAndLockExternalTasksRequest]) (*connect.Response[endpoints.FetchAndLockExternalTasksResponse], error) {
	return c.fetchAndLockExternalTasks.CallUnary(ctx, req)
}

// CompleteExternalTask calls process.ExternalTaskService.CompleteExternalTask.
func (c *externalTaskServiceClient) CompleteExternalTask(ctx context.Context, req *connect.Request[endpoints.CompleteExternalTaskRequest]) (*connect.Response[endpoints.CompleteExternalTaskResponse], error) {
	return c.completeExternalTask.CallUnary(ctx, req)
}

// HandleExternalTaskFailure calls process.ExternalTaskService.HandleExternalTaskFailure.
func (c *externalTaskServiceClient) HandleExternalTaskFailure(ctx context.Context, req *connect.Request[endpoints.HandleExternalTaskFailureRequest]) (*connect.Response[endpoints.HandleExternalTaskFailureResponse], error) {
	return c.handleExternalTaskFailure.CallUnary(ctx, req)
}

// ExternalTaskServiceHandler is an implementation of the process.ExternalTaskService service.
type ExternalTaskServiceHandler interface {
	FetchAndLockExternalTasks(context.Context, *connect.Request[endpoints.FetchAndLockExternalTasksRequest]) (*connect.Response[endpoints.FetchAndLockExternalTasksResponse], error)
	CompleteExternalTask(context.Context, *connect.Request[endpoints.CompleteExternalTaskRequest]) (*connect.Response[endpoints.CompleteExternalTaskResponse], error)
	HandleExternalTaskFailure(context.Context, *connect.Request[endpoints.HandleExternalTaskFailureRequest]) (*connect.Response[endpoints.HandleExternalTaskFailureResponse], error)
}

// NewExternalTaskServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExternalTaskServiceHandler(svc ExternalTaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	externalTaskServiceMethods := services.File_services_external_task_proto.Services().ByName("ExternalTaskService").Methods()
	externalTaskServiceFetchAndLockExternalTasksHandler := connect.NewUnaryHandler(
		ExternalTaskServiceFetchAndLockExternalTasksProcedure,
		svc.FetchAndLockExternalTasks,
		connect.WithSchema(externalTaskServiceMethods.ByName("FetchAndLockExternalTasks")),
		connect.WithHandlerOptions(opts...),
	)
	externalTaskServiceCompleteExternalTaskHandler := connect.NewUnaryHandler(
		ExternalTaskServiceCompleteExternalTaskProcedure,
		svc.CompleteExternalTask,
		connect.WithSchema(externalTaskServiceMethods.ByName("CompleteExternalTask")),
		connect.WithHandlerOptions(opts...),
	)
	externalTaskServiceHandleExternalTaskFailureHandler := connect.NewUnaryHandler(
		ExternalTaskServiceHandleExternalTaskFailureProcedure,
		svc.HandleExternalTaskFailure,
		connect.WithSchema(externalTaskServiceMethods.ByName("HandleExternalTaskFailure")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.ExternalTaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExternalTaskServiceFetchAndLockExternalTasksProcedure:
			externalTaskServiceFetchAndLockExternalTasksHandler.ServeHTTP(w, r)
		case ExternalTaskServiceCompleteExternalTaskProcedure:
			externalTaskServiceCompleteExternalTaskHandler.ServeHTTP(w, r)
		case ExternalTaskServiceHandleExternalTaskFailureProcedure:
			externalTaskServiceHandleExternalTaskFailureHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExternalTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExternalTaskServiceHandler struct{}

func (UnimplementedExternalTaskServiceHandler) FetchAndLockExternalTasks(context.Context, *connect.Request[endpoints.FetchAndLockExternalTasksRequest]) (*connect.Response[endpoints.FetchAndLockExternalTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ExternalTaskService.FetchAndLockExternalTasks is not implemented"))
}

func (UnimplementedExternalTaskServiceHandler) CompleteExternalTask(context.Context, *connect.Request[endpoints.CompleteExternalTaskRequest]) (*connect.Response[endpoints.CompleteExternalTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ExternalTaskService.CompleteExternalTask is not implemented"))
}

func (UnimplementedExternalTaskServiceHandler) HandleExternalTaskFailure(context.Context, *connect.Request[endpoints.HandleExternalTaskFailureRequest]) (*connect.Response[endpoints.HandleExternalTaskFailureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ExternalTaskService.HandleExternalTaskFailure is not implemented"))
}
