// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/notification.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "process.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceListNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListNotifications RPC.
	NotificationServiceListNotificationsProcedure = "/process.NotificationService/ListNotifications"
	// NotificationServiceMarkAsReadProcedure is the fully-qualified name of the NotificationService's
	// MarkAsRead RPC.
	NotificationServiceMarkAsReadProcedure = "/process.NotificationService/MarkAsRead"
	// NotificationServiceMarkAllAsReadProcedure is the fully-qualified name of the
	// NotificationService's MarkAllAsRead RPC.
	NotificationServiceMarkAllAsReadProcedure = "/process.NotificationService/MarkAllAsRead"
	// NotificationServiceDeleteNotificationProcedure is the fully-qualified name of the
	// NotificationService's DeleteNotification RPC.
	NotificationServiceDeleteNotificationProcedure = "/process.NotificationService/DeleteNotification"
)

// NotificationServiceClient is a client for the process.NotificationService service.
type NotificationServiceClient interface {
	ListNotifications(context.Context, *connect.Request[services.ListNotificationsRequest]) (*connect.Response[services.ListNotificationsResponse], error)
	MarkAsRead(context.Context, *connect.Request[services.MarkAsReadRequest]) (*connect.Response[services.MarkAsReadResponse], error)
	MarkAllAsRead(context.Context, *connect.Request[services.MarkAllAsReadRequest]) (*connect.Response[services.MarkAllAsReadResponse], error)
	DeleteNotification(context.Context, *connect.Request[services.DeleteNotificationRequest]) (*connect.Response[services.DeleteNotificationResponse], error)
}

// NewNotificationServiceClient constructs a client for the process.NotificationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := services.File_services_notification_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		listNotifications: connect.NewClient[services.ListNotificationsRequest, services.ListNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
			connect.WithClientOptions(opts...),
		),
		markAsRead: connect.NewClient[services.MarkAsReadRequest, services.MarkAsReadResponse](
			httpClient,
			baseURL+NotificationServiceMarkAsReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkAsRead")),
			connect.WithClientOptions(opts...),
		),
		markAllAsRead: connect.NewClient[services.MarkAllAsReadRequest, services.MarkAllAsReadResponse](
			httpClient,
			baseURL+NotificationServiceMarkAllAsReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkAllAsRead")),
			connect.WithClientOptions(opts...),
		),
		deleteNotification: connect.NewClient[services.DeleteNotificationRequest, services.DeleteNotificationResponse](
			httpClient,
			baseURL+NotificationServiceDeleteNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("DeleteNotification")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	listNotifications  *connect.Client[services.ListNotificationsRequest, services.ListNotificationsResponse]
	markAsRead         *connect.Client[services.MarkAsReadRequest, services.MarkAsReadResponse]
	markAllAsRead      *connect.Client[services.MarkAllAsReadRequest, services.MarkAllAsReadResponse]
	deleteNotification *connect.Client[services.DeleteNotificationRequest, services.DeleteNotificationResponse]
}

// ListNotifications calls process.NotificationService.ListNotifications.
func (c *notificationServiceClient) ListNotifications(ctx context.Context, req *connect.Request[services.ListNotificationsRequest]) (*connect.Response[services.ListNotificationsResponse], error) {
	return c.listNotifications.CallUnary(ctx, req)
}

// MarkAsRead calls process.NotificationService.MarkAsRead.
func (c *notificationServiceClient) MarkAsRead(ctx context.Context, req *connect.Request[services.MarkAsReadRequest]) (*connect.Response[services.MarkAsReadResponse], error) {
	return c.markAsRead.CallUnary(ctx, req)
}

// MarkAllAsRead calls process.NotificationService.MarkAllAsRead.
func (c *notificationServiceClient) MarkAllAsRead(ctx context.Context, req *connect.Request[services.MarkAllAsReadRequest]) (*connect.Response[services.MarkAllAsReadResponse], error) {
	return c.markAllAsRead.CallUnary(ctx, req)
}

// DeleteNotification calls process.NotificationService.DeleteNotification.
func (c *notificationServiceClient) DeleteNotification(ctx context.Context, req *connect.Request[services.DeleteNotificationRequest]) (*connect.Response[services.DeleteNotificationResponse], error) {
	return c.deleteNotification.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the process.NotificationService service.
type NotificationServiceHandler interface {
	ListNotifications(context.Context, *connect.Request[services.ListNotificationsRequest]) (*connect.Response[services.ListNotificationsResponse], error)
	MarkAsRead(context.Context, *connect.Request[services.MarkAsReadRequest]) (*connect.Response[services.MarkAsReadResponse], error)
	MarkAllAsRead(context.Context, *connect.Request[services.MarkAllAsReadRequest]) (*connect.Response[services.MarkAllAsReadResponse], error)
	DeleteNotification(context.Context, *connect.Request[services.DeleteNotificationRequest]) (*connect.Response[services.DeleteNotificationResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := services.File_services_notification_proto.Services().ByName("NotificationService").Methods()
	notificationServiceListNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListNotificationsProcedure,
		svc.ListNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkAsReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkAsReadProcedure,
		svc.MarkAsRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkAsRead")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkAllAsReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkAllAsReadProcedure,
		svc.MarkAllAsRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkAllAsRead")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceDeleteNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceDeleteNotificationProcedure,
		svc.DeleteNotification,
		connect.WithSchema(notificationServiceMethods.ByName("DeleteNotification")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceListNotificationsProcedure:
			notificationServiceListNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceMarkAsReadProcedure:
			notificationServiceMarkAsReadHandler.ServeHTTP(w, r)
		case NotificationServiceMarkAllAsReadProcedure:
			notificationServiceMarkAllAsReadHandler.ServeHTTP(w, r)
		case NotificationServiceDeleteNotificationProcedure:
			notificationServiceDeleteNotificationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) ListNotifications(context.Context, *connect.Request[services.ListNotificationsRequest]) (*connect.Response[services.ListNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.NotificationService.ListNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkAsRead(context.Context, *connect.Request[services.MarkAsReadRequest]) (*connect.Response[services.MarkAsReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.NotificationService.MarkAsRead is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkAllAsRead(context.Context, *connect.Request[services.MarkAllAsReadRequest]) (*connect.Response[services.MarkAllAsReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.NotificationService.MarkAllAsRead is not implemented"))
}

func (UnimplementedNotificationServiceHandler) DeleteNotification(context.Context, *connect.Request[services.DeleteNotificationRequest]) (*connect.Response[services.DeleteNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.NotificationService.DeleteNotification is not implemented"))
}
