// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/organization.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrganizationServiceName is the fully-qualified name of the OrganizationService service.
	OrganizationServiceName = "process.OrganizationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrganizationServiceCreateOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's CreateOrganization RPC.
	OrganizationServiceCreateOrganizationProcedure = "/process.OrganizationService/CreateOrganization"
	// OrganizationServiceGetOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's GetOrganization RPC.
	OrganizationServiceGetOrganizationProcedure = "/process.OrganizationService/GetOrganization"
	// OrganizationServiceListOrganizationsProcedure is the fully-qualified name of the
	// OrganizationService's ListOrganizations RPC.
	OrganizationServiceListOrganizationsProcedure = "/process.OrganizationService/ListOrganizations"
	// OrganizationServiceUpdateOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's UpdateOrganization RPC.
	OrganizationServiceUpdateOrganizationProcedure = "/process.OrganizationService/UpdateOrganization"
	// OrganizationServiceDeleteOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's DeleteOrganization RPC.
	OrganizationServiceDeleteOrganizationProcedure = "/process.OrganizationService/DeleteOrganization"
)

// OrganizationServiceClient is a client for the process.OrganizationService service.
type OrganizationServiceClient interface {
	CreateOrganization(context.Context, *connect.Request[endpoints.CreateOrganizationRequest]) (*connect.Response[endpoints.CreateOrganizationResponse], error)
	GetOrganization(context.Context, *connect.Request[endpoints.GetOrganizationRequest]) (*connect.Response[endpoints.GetOrganizationResponse], error)
	ListOrganizations(context.Context, *connect.Request[endpoints.ListOrganizationsRequest]) (*connect.Response[endpoints.ListOrganizationsResponse], error)
	UpdateOrganization(context.Context, *connect.Request[endpoints.UpdateOrganizationRequest]) (*connect.Response[endpoints.UpdateOrganizationResponse], error)
	DeleteOrganization(context.Context, *connect.Request[endpoints.DeleteOrganizationRequest]) (*connect.Response[endpoints.DeleteOrganizationResponse], error)
}

// NewOrganizationServiceClient constructs a client for the process.OrganizationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrganizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrganizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	organizationServiceMethods := services.File_services_organization_proto.Services().ByName("OrganizationService").Methods()
	return &organizationServiceClient{
		createOrganization: connect.NewClient[endpoints.CreateOrganizationRequest, endpoints.CreateOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceCreateOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		getOrganization: connect.NewClient[endpoints.GetOrganizationRequest, endpoints.GetOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceGetOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
			connect.WithClientOptions(opts...),
		),
		listOrganizations: connect.NewClient[endpoints.ListOrganizationsRequest, endpoints.ListOrganizationsResponse](
			httpClient,
			baseURL+OrganizationServiceListOrganizationsProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
			connect.WithClientOptions(opts...),
		),
		updateOrganization: connect.NewClient[endpoints.UpdateOrganizationRequest, endpoints.UpdateOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceUpdateOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("UpdateOrganization")),
			connect.WithClientOptions(opts...),
		),
		deleteOrganization: connect.NewClient[endpoints.DeleteOrganizationRequest, endpoints.DeleteOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceDeleteOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("DeleteOrganization")),
			connect.WithClientOptions(opts...),
		),
	}
}

// organizationServiceClient implements OrganizationServiceClient.
type organizationServiceClient struct {
	createOrganization *connect.Client[endpoints.CreateOrganizationRequest, endpoints.CreateOrganizationResponse]
	getOrganization    *connect.Client[endpoints.GetOrganizationRequest, endpoints.GetOrganizationResponse]
	listOrganizations  *connect.Client[endpoints.ListOrganizationsRequest, endpoints.ListOrganizationsResponse]
	updateOrganization *connect.Client[endpoints.UpdateOrganizationRequest, endpoints.UpdateOrganizationResponse]
	deleteOrganization *connect.Client[endpoints.DeleteOrganizationRequest, endpoints.DeleteOrganizationResponse]
}

// CreateOrganization calls process.OrganizationService.CreateOrganization.
func (c *organizationServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[endpoints.CreateOrganizationRequest]) (*connect.Response[endpoints.CreateOrganizationResponse], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// GetOrganization calls process.OrganizationService.GetOrganization.
func (c *organizationServiceClient) GetOrganization(ctx context.Context, req *connect.Request[endpoints.GetOrganizationRequest]) (*connect.Response[endpoints.GetOrganizationResponse], error) {
	return c.getOrganization.CallUnary(ctx, req)
}

// ListOrganizations calls process.OrganizationService.ListOrganizations.
func (c *organizationServiceClient) ListOrganizations(ctx context.Context, req *connect.Request[endpoints.ListOrganizationsRequest]) (*connect.Response[endpoints.ListOrganizationsResponse], error) {
	return c.listOrganizations.CallUnary(ctx, req)
}

// UpdateOrganization calls process.OrganizationService.UpdateOrganization.
func (c *organizationServiceClient) UpdateOrganization(ctx context.Context, req *connect.Request[endpoints.UpdateOrganizationRequest]) (*connect.Response[endpoints.UpdateOrganizationResponse], error) {
	return c.updateOrganization.CallUnary(ctx, req)
}

// DeleteOrganization calls process.OrganizationService.DeleteOrganization.
func (c *organizationServiceClient) DeleteOrganization(ctx context.Context, req *connect.Request[endpoints.DeleteOrganizationRequest]) (*connect.Response[endpoints.DeleteOrganizationResponse], error) {
	return c.deleteOrganization.CallUnary(ctx, req)
}

// OrganizationServiceHandler is an implementation of the process.OrganizationService service.
type OrganizationServiceHandler interface {
	CreateOrganization(context.Context, *connect.Request[endpoints.CreateOrganizationRequest]) (*connect.Response[endpoints.CreateOrganizationResponse], error)
	GetOrganization(context.Context, *connect.Request[endpoints.GetOrganizationRequest]) (*connect.Response[endpoints.GetOrganizationResponse], error)
	ListOrganizations(context.Context, *connect.Request[endpoints.ListOrganizationsRequest]) (*connect.Response[endpoints.ListOrganizationsResponse], error)
	UpdateOrganization(context.Context, *connect.Request[endpoints.UpdateOrganizationRequest]) (*connect.Response[endpoints.UpdateOrganizationResponse], error)
	DeleteOrganization(context.Context, *connect.Request[endpoints.DeleteOrganizationRequest]) (*connect.Response[endpoints.DeleteOrganizationResponse], error)
}

// NewOrganizationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrganizationServiceHandler(svc OrganizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	organizationServiceMethods := services.File_services_organization_proto.Services().ByName("OrganizationService").Methods()
	organizationServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceGetOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceGetOrganizationProcedure,
		svc.GetOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceListOrganizationsHandler := connect.NewUnaryHandler(
		OrganizationServiceListOrganizationsProcedure,
		svc.ListOrganizations,
		connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceUpdateOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceUpdateOrganizationProcedure,
		svc.UpdateOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("UpdateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceDeleteOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceDeleteOrganizationProcedure,
		svc.DeleteOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("DeleteOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.OrganizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrganizationServiceCreateOrganizationProcedure:
			organizationServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceGetOrganizationProcedure:
			organizationServiceGetOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceListOrganizationsProcedure:
			organizationServiceListOrganizationsHandler.ServeHTTP(w, r)
		case OrganizationServiceUpdateOrganizationProcedure:
			organizationServiceUpdateOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceDeleteOrganizationProcedure:
			organizationServiceDeleteOrganizationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrganizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrganizationServiceHandler struct{}

func (UnimplementedOrganizationServiceHandler) CreateOrganization(context.Context, *connect.Request[endpoints.CreateOrganizationRequest]) (*connect.Response[endpoints.CreateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.OrganizationService.CreateOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) GetOrganization(context.Context, *connect.Request[endpoints.GetOrganizationRequest]) (*connect.Response[endpoints.GetOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.OrganizationService.GetOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) ListOrganizations(context.Context, *connect.Request[endpoints.ListOrganizationsRequest]) (*connect.Response[endpoints.ListOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.OrganizationService.ListOrganizations is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) UpdateOrganization(context.Context, *connect.Request[endpoints.UpdateOrganizationRequest]) (*connect.Response[endpoints.UpdateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.OrganizationService.UpdateOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) DeleteOrganization(context.Context, *connect.Request[endpoints.DeleteOrganizationRequest]) (*connect.Response[endpoints.DeleteOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.OrganizationService.DeleteOrganization is not implemented"))
}
