// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/process.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProcessServiceName is the fully-qualified name of the ProcessService service.
	ProcessServiceName = "process.ProcessService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProcessServiceStartProcessProcedure is the fully-qualified name of the ProcessService's
	// StartProcess RPC.
	ProcessServiceStartProcessProcedure = "/process.ProcessService/StartProcess"
	// ProcessServiceGetInstanceProcedure is the fully-qualified name of the ProcessService's
	// GetInstance RPC.
	ProcessServiceGetInstanceProcedure = "/process.ProcessService/GetInstance"
	// ProcessServiceListInstancesProcedure is the fully-qualified name of the ProcessService's
	// ListInstances RPC.
	ProcessServiceListInstancesProcedure = "/process.ProcessService/ListInstances"
	// ProcessServiceGetExecutionPathProcedure is the fully-qualified name of the ProcessService's
	// GetExecutionPath RPC.
	ProcessServiceGetExecutionPathProcedure = "/process.ProcessService/GetExecutionPath"
)

// ProcessServiceClient is a client for the process.ProcessService service.
type ProcessServiceClient interface {
	StartProcess(context.Context, *connect.Request[endpoints.StartProcessRequest]) (*connect.Response[endpoints.StartProcessResponse], error)
	GetInstance(context.Context, *connect.Request[endpoints.GetInstanceRequest]) (*connect.Response[endpoints.GetInstanceResponse], error)
	ListInstances(context.Context, *connect.Request[endpoints.ListInstancesRequest]) (*connect.Response[endpoints.ListInstancesResponse], error)
	GetExecutionPath(context.Context, *connect.Request[endpoints.GetExecutionPathRequest]) (*connect.Response[endpoints.GetExecutionPathResponse], error)
}

// NewProcessServiceClient constructs a client for the process.ProcessService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processServiceMethods := services.File_services_process_proto.Services().ByName("ProcessService").Methods()
	return &processServiceClient{
		startProcess: connect.NewClient[endpoints.StartProcessRequest, endpoints.StartProcessResponse](
			httpClient,
			baseURL+ProcessServiceStartProcessProcedure,
			connect.WithSchema(processServiceMethods.ByName("StartProcess")),
			connect.WithClientOptions(opts...),
		),
		getInstance: connect.NewClient[endpoints.GetInstanceRequest, endpoints.GetInstanceResponse](
			httpClient,
			baseURL+ProcessServiceGetInstanceProcedure,
			connect.WithSchema(processServiceMethods.ByName("GetInstance")),
			connect.WithClientOptions(opts...),
		),
		listInstances: connect.NewClient[endpoints.ListInstancesRequest, endpoints.ListInstancesResponse](
			httpClient,
			baseURL+ProcessServiceListInstancesProcedure,
			connect.WithSchema(processServiceMethods.ByName("ListInstances")),
			connect.WithClientOptions(opts...),
		),
		getExecutionPath: connect.NewClient[endpoints.GetExecutionPathRequest, endpoints.GetExecutionPathResponse](
			httpClient,
			baseURL+ProcessServiceGetExecutionPathProcedure,
			connect.WithSchema(processServiceMethods.ByName("GetExecutionPath")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processServiceClient implements ProcessServiceClient.
type processServiceClient struct {
	startProcess     *connect.Client[endpoints.StartProcessRequest, endpoints.StartProcessResponse]
	getInstance      *connect.Client[endpoints.GetInstanceRequest, endpoints.GetInstanceResponse]
	listInstances    *connect.Client[endpoints.ListInstancesRequest, endpoints.ListInstancesResponse]
	getExecutionPath *connect.Client[endpoints.GetExecutionPathRequest, endpoints.GetExecutionPathResponse]
}

// StartProcess calls process.ProcessService.StartProcess.
func (c *processServiceClient) StartProcess(ctx context.Context, req *connect.Request[endpoints.StartProcessRequest]) (*connect.Response[endpoints.StartProcessResponse], error) {
	return c.startProcess.CallUnary(ctx, req)
}

// GetInstance calls process.ProcessService.GetInstance.
func (c *processServiceClient) GetInstance(ctx context.Context, req *connect.Request[endpoints.GetInstanceRequest]) (*connect.Response[endpoints.GetInstanceResponse], error) {
	return c.getInstance.CallUnary(ctx, req)
}

// ListInstances calls process.ProcessService.ListInstances.
func (c *processServiceClient) ListInstances(ctx context.Context, req *connect.Request[endpoints.ListInstancesRequest]) (*connect.Response[endpoints.ListInstancesResponse], error) {
	return c.listInstances.CallUnary(ctx, req)
}

// GetExecutionPath calls process.ProcessService.GetExecutionPath.
func (c *processServiceClient) GetExecutionPath(ctx context.Context, req *connect.Request[endpoints.GetExecutionPathRequest]) (*connect.Response[endpoints.GetExecutionPathResponse], error) {
	return c.getExecutionPath.CallUnary(ctx, req)
}

// ProcessServiceHandler is an implementation of the process.ProcessService service.
type ProcessServiceHandler interface {
	StartProcess(context.Context, *connect.Request[endpoints.StartProcessRequest]) (*connect.Response[endpoints.StartProcessResponse], error)
	GetInstance(context.Context, *connect.Request[endpoints.GetInstanceRequest]) (*connect.Response[endpoints.GetInstanceResponse], error)
	ListInstances(context.Context, *connect.Request[endpoints.ListInstancesRequest]) (*connect.Response[endpoints.ListInstancesResponse], error)
	GetExecutionPath(context.Context, *connect.Request[endpoints.GetExecutionPathRequest]) (*connect.Response[endpoints.GetExecutionPathResponse], error)
}

// NewProcessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessServiceHandler(svc ProcessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processServiceMethods := services.File_services_process_proto.Services().ByName("ProcessService").Methods()
	processServiceStartProcessHandler := connect.NewUnaryHandler(
		ProcessServiceStartProcessProcedure,
		svc.StartProcess,
		connect.WithSchema(processServiceMethods.ByName("StartProcess")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceGetInstanceHandler := connect.NewUnaryHandler(
		ProcessServiceGetInstanceProcedure,
		svc.GetInstance,
		connect.WithSchema(processServiceMethods.ByName("GetInstance")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceListInstancesHandler := connect.NewUnaryHandler(
		ProcessServiceListInstancesProcedure,
		svc.ListInstances,
		connect.WithSchema(processServiceMethods.ByName("ListInstances")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceGetExecutionPathHandler := connect.NewUnaryHandler(
		ProcessServiceGetExecutionPathProcedure,
		svc.GetExecutionPath,
		connect.WithSchema(processServiceMethods.ByName("GetExecutionPath")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.ProcessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessServiceStartProcessProcedure:
			processServiceStartProcessHandler.ServeHTTP(w, r)
		case ProcessServiceGetInstanceProcedure:
			processServiceGetInstanceHandler.ServeHTTP(w, r)
		case ProcessServiceListInstancesProcedure:
			processServiceListInstancesHandler.ServeHTTP(w, r)
		case ProcessServiceGetExecutionPathProcedure:
			processServiceGetExecutionPathHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessServiceHandler struct{}

func (UnimplementedProcessServiceHandler) StartProcess(context.Context, *connect.Request[endpoints.StartProcessRequest]) (*connect.Response[endpoints.StartProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ProcessService.StartProcess is not implemented"))
}

func (UnimplementedProcessServiceHandler) GetInstance(context.Context, *connect.Request[endpoints.GetInstanceRequest]) (*connect.Response[endpoints.GetInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ProcessService.GetInstance is not implemented"))
}

func (UnimplementedProcessServiceHandler) ListInstances(context.Context, *connect.Request[endpoints.ListInstancesRequest]) (*connect.Response[endpoints.ListInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ProcessService.ListInstances is not implemented"))
}

func (UnimplementedProcessServiceHandler) GetExecutionPath(context.Context, *connect.Request[endpoints.GetExecutionPathRequest]) (*connect.Response[endpoints.GetExecutionPathResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.ProcessService.GetExecutionPath is not implemented"))
}
