// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/signal.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SignalServiceName is the fully-qualified name of the SignalService service.
	SignalServiceName = "process.SignalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SignalServiceBroadcastSignalProcedure is the fully-qualified name of the SignalService's
	// BroadcastSignal RPC.
	SignalServiceBroadcastSignalProcedure = "/process.SignalService/BroadcastSignal"
	// SignalServiceSendMessageProcedure is the fully-qualified name of the SignalService's SendMessage
	// RPC.
	SignalServiceSendMessageProcedure = "/process.SignalService/SendMessage"
)

// SignalServiceClient is a client for the process.SignalService service.
type SignalServiceClient interface {
	BroadcastSignal(context.Context, *connect.Request[endpoints.BroadcastSignalRequest]) (*connect.Response[endpoints.BroadcastSignalResponse], error)
	SendMessage(context.Context, *connect.Request[endpoints.SendMessageRequest]) (*connect.Response[endpoints.SendMessageResponse], error)
}

// NewSignalServiceClient constructs a client for the process.SignalService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSignalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SignalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	signalServiceMethods := services.File_services_signal_proto.Services().ByName("SignalService").Methods()
	return &signalServiceClient{
		broadcastSignal: connect.NewClient[endpoints.BroadcastSignalRequest, endpoints.BroadcastSignalResponse](
			httpClient,
			baseURL+SignalServiceBroadcastSignalProcedure,
			connect.WithSchema(signalServiceMethods.ByName("BroadcastSignal")),
			connect.WithClientOptions(opts...),
		),
		sendMessage: connect.NewClient[endpoints.SendMessageRequest, endpoints.SendMessageResponse](
			httpClient,
			baseURL+SignalServiceSendMessageProcedure,
			connect.WithSchema(signalServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// signalServiceClient implements SignalServiceClient.
type signalServiceClient struct {
	broadcastSignal *connect.Client[endpoints.BroadcastSignalRequest, endpoints.BroadcastSignalResponse]
	sendMessage     *connect.Client[endpoints.SendMessageRequest, endpoints.SendMessageResponse]
}

// BroadcastSignal calls process.SignalService.BroadcastSignal.
func (c *signalServiceClient) BroadcastSignal(ctx context.Context, req *connect.Request[endpoints.BroadcastSignalRequest]) (*connect.Response[endpoints.BroadcastSignalResponse], error) {
	return c.broadcastSignal.CallUnary(ctx, req)
}

// SendMessage calls process.SignalService.SendMessage.
func (c *signalServiceClient) SendMessage(ctx context.Context, req *connect.Request[endpoints.SendMessageRequest]) (*connect.Response[endpoints.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// SignalServiceHandler is an implementation of the process.SignalService service.
type SignalServiceHandler interface {
	BroadcastSignal(context.Context, *connect.Request[endpoints.BroadcastSignalRequest]) (*connect.Response[endpoints.BroadcastSignalResponse], error)
	SendMessage(context.Context, *connect.Request[endpoints.SendMessageRequest]) (*connect.Response[endpoints.SendMessageResponse], error)
}

// NewSignalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSignalServiceHandler(svc SignalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	signalServiceMethods := services.File_services_signal_proto.Services().ByName("SignalService").Methods()
	signalServiceBroadcastSignalHandler := connect.NewUnaryHandler(
		SignalServiceBroadcastSignalProcedure,
		svc.BroadcastSignal,
		connect.WithSchema(signalServiceMethods.ByName("BroadcastSignal")),
		connect.WithHandlerOptions(opts...),
	)
	signalServiceSendMessageHandler := connect.NewUnaryHandler(
		SignalServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(signalServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.SignalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SignalServiceBroadcastSignalProcedure:
			signalServiceBroadcastSignalHandler.ServeHTTP(w, r)
		case SignalServiceSendMessageProcedure:
			signalServiceSendMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSignalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSignalServiceHandler struct{}

func (UnimplementedSignalServiceHandler) BroadcastSignal(context.Context, *connect.Request[endpoints.BroadcastSignalRequest]) (*connect.Response[endpoints.BroadcastSignalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.SignalService.BroadcastSignal is not implemented"))
}

func (UnimplementedSignalServiceHandler) SendMessage(context.Context, *connect.Request[endpoints.SendMessageRequest]) (*connect.Response[endpoints.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.SignalService.SendMessage is not implemented"))
}
