// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/user.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	services "github.com/gsoultan/metis/api/proto/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "process.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/process.UserService/GetUser"
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/process.UserService/ListUsers"
)

// UserServiceClient is a client for the process.UserService service.
type UserServiceClient interface {
	GetUser(context.Context, *connect.Request[endpoints.GetUserRequest]) (*connect.Response[endpoints.GetUserResponse], error)
	ListUsers(context.Context, *connect.Request[endpoints.ListUsersRequest]) (*connect.Response[endpoints.ListUsersResponse], error)
}

// NewUserServiceClient constructs a client for the process.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := services.File_services_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getUser: connect.NewClient[endpoints.GetUserRequest, endpoints.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[endpoints.ListUsersRequest, endpoints.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUser   *connect.Client[endpoints.GetUserRequest, endpoints.GetUserResponse]
	listUsers *connect.Client[endpoints.ListUsersRequest, endpoints.ListUsersResponse]
}

// GetUser calls process.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[endpoints.GetUserRequest]) (*connect.Response[endpoints.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListUsers calls process.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[endpoints.ListUsersRequest]) (*connect.Response[endpoints.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the process.UserService service.
type UserServiceHandler interface {
	GetUser(context.Context, *connect.Request[endpoints.GetUserRequest]) (*connect.Response[endpoints.GetUserResponse], error)
	ListUsers(context.Context, *connect.Request[endpoints.ListUsersRequest]) (*connect.Response[endpoints.ListUsersResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := services.File_services_user_proto.Services().ByName("UserService").Methods()
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[endpoints.GetUserRequest]) (*connect.Response[endpoints.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[endpoints.ListUsersRequest]) (*connect.Response[endpoints.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.UserService.ListUsers is not implemented"))
}
