#!/usr/bin/env bash
#
# Start Metis BPM for local development: the Go backend and the Vite dev
# server, together, with one Ctrl-C stopping both.
#
#   ./scripts/dev.sh              backend + UI (default)
#   ./scripts/dev.sh backend      backend only
#   ./scripts/dev.sh ui           UI only
#   ./scripts/dev.sh --reset      wipe the local SQLite database first
#   ./scripts/dev.sh --sample     set up and fill it with worked examples
#
# The UI runs on :5273 and proxies /api to the backend on :8080, so
# development is same-origin — the app talks to the server exactly as it does
# in production, and no CORS is involved.

set -Eeuo pipefail

readonly ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Not Vite's default 5173 — it collides with every other Vite project on the
# machine. Override with UI_PORT for a one-off run.
readonly UI_PORT="${UI_PORT:-5273}"
readonly API_PORT="${API_PORT:-8080}"

# Ports this run actually bound, so shutdown only reports its own.
STARTED_PORTS=()
readonly GRPC_PORT="${GRPC_PORT:-8081}"
readonly ENV_FILE="$ROOT/.env.development"
readonly DB_FILE="$ROOT/gobpm.db"

# --- output ----------------------------------------------------------------

if [[ -t 1 ]]; then
  readonly C_RESET=$'\033[0m' C_DIM=$'\033[2m' C_BOLD=$'\033[1m'
  readonly C_RED=$'\033[31m' C_GREEN=$'\033[32m' C_YELLOW=$'\033[33m' C_BLUE=$'\033[34m'
else
  readonly C_RESET='' C_DIM='' C_BOLD='' C_RED='' C_GREEN='' C_YELLOW='' C_BLUE=''
fi

info()  { printf '%s==>%s %s\n' "$C_BLUE$C_BOLD" "$C_RESET" "$*"; }
warn()  { printf '%s warn%s %s\n' "$C_YELLOW$C_BOLD" "$C_RESET" "$*" >&2; }
die()   { printf '%serror%s %s\n' "$C_RED$C_BOLD" "$C_RESET" "$*" >&2; exit 1; }
ok()    { printf '%s  ok%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }

# --- prerequisites ---------------------------------------------------------

require() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is not installed. $2"
}

check_prerequisites() {
  require go   "Install Go 1.26.5+ from https://go.dev/dl/"
  require bun  "Install Bun from https://bun.sh (or run: brew install oven-sh/bun/bun)"

  local want=1.26 have
  have="$(go env GOVERSION)"; have="${have#go}"
  if [[ "$(printf '%s\n%s\n' "$want" "$have" | sort -V | head -1)" != "$want" ]]; then
    warn "Go $have is older than the $want required by go.mod; the build may fail."
  fi
}

port_in_use() {
  lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
}

# port_holder describes what is listening, as "command (pid 1234)".
#
# "Port in use" on its own sends you to look it up; the script already has to
# ask the same question to know, so it may as well say.
port_holder() {
  lsof -nP -iTCP:"$1" -sTCP:LISTEN -Fcp 2>/dev/null |
    awk '/^p/{pid=substr($0,2)} /^c/{print substr($0,2) " (pid " pid ")"; exit}'
}

# check_ports reports every conflict, not just the first.
#
# Backend and UI ports are usually taken by the same stale run, and being told
# about one, freeing it and being told about the next is a poor way to find
# that out.
check_ports() {
  local port held=()
  for port in "$@"; do
    if port_in_use "$port"; then
      held+=("  port $port is used by $(port_holder "$port")")
    fi
  done

  (( ${#held[@]} == 0 )) && return 0

  printf '%s\n' "${held[@]}" >&2
  die "stop the process using it, or set API_PORT/UI_PORT to something free"
}

# --- secrets ---------------------------------------------------------------

random_secret() {
  # LC_ALL=C keeps tr from choking on non-UTF-8 bytes from /dev/urandom.
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48
}

# Generate development secrets once and reuse them.
#
# The server refuses to start without ENCRYPTION_KEY (process and task
# variables are encrypted at rest) and without JWT_SECRET once configured.
# Persisting them matters: a fresh ENCRYPTION_KEY cannot read data written
# with the previous one, and a fresh JWT_SECRET invalidates every session on
# each restart.
ensure_dev_env() {
  if [[ -f "$ENV_FILE" ]]; then
    return
  fi

  info "Generating development secrets in .env.development"
  cat >"$ENV_FILE" <<EOF
# Local development secrets — generated by scripts/dev.sh, gitignored.
#
# These are NOT suitable for any shared or production environment. Rotating
# ENCRYPTION_KEY makes existing process/task variables unreadable; rotating
# JWT_SECRET logs everyone out.
ENCRYPTION_KEY=$(random_secret)
JWT_SECRET=$(random_secret)

# Egress policy blocks private addresses by default, which would also block a
# service task pointed at a mock API on localhost.
GOBPM_HTTP_ALLOW_PRIVATE_NETWORKS=true

# Uncomment to run against PostgreSQL instead of the default SQLite file.
# DATABASE_URL=postgres://gobpm:gobpm@localhost:5432/gobpm?sslmode=disable

# Uncomment to keep the pre-existing gateway fallback while migrating
# definitions that relied on it.
# GOBPM_ALLOW_IMPLICIT_DEFAULT_FLOW=true
EOF
  ok "wrote $ENV_FILE"
}

load_dev_env() {
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a

  # Once the setup wizard has run, config.yaml holds the key the data was
  # actually encrypted with. Exporting the generated one on top of it caused
  # the server to start with the wrong key and fail to decrypt its own
  # connection string — which looked, from the browser, like the system had
  # never been set up.
  if [[ -f "$ROOT/config.yaml" ]]; then
    unset ENCRYPTION_KEY
    unset JWT_SECRET
  fi
}

# --- processes -------------------------------------------------------------

PIDS=()

# Stop every child and verify nothing is left holding a port.
#
# `go run` compiles to a temporary binary and execs it as a child, so signalling
# only the job leader leaves the real server running and the port bound — the
# single most annoying way for a dev script to fail. Each job is its own process
# group (see run_prefixed), so signal the group, then escalate to KILL for
# anything that ignored TERM.
shutdown() {
  local pid sig
  trap - INT TERM HUP EXIT
  # Turn job control back off so bash does not print its own
  # "Terminated: 15" notice for each job we are deliberately stopping.
  set +m
  printf '\n'
  info "Shutting down"

  for sig in TERM KILL; do
    local alive=0
    for pid in "${PIDS[@]:-}"; do
      [[ -n "$pid" ]] || continue
      if kill -0 "$pid" 2>/dev/null || kill -0 -- -"$pid" 2>/dev/null; then
        alive=1
        kill -"$sig" -- -"$pid" 2>/dev/null || kill -"$sig" "$pid" 2>/dev/null || true
      fi
    done
    (( alive )) || break
    [[ "$sig" == TERM ]] && sleep 2
  done

  wait 2>/dev/null || true
  report_orphans
  ok "stopped"
}

# Warn loudly rather than leaving a silently bound port for the next run to
# trip over.
#
# Only ports this run bound are checked. The trap used to be installed before
# the preflight, so failing to start — because something else already held the
# port — printed "shutting down" and then blamed itself for a port it had never
# taken, which reads as a broken shutdown and sends you after the wrong thing.
report_orphans() {
  local port held=0
  # bash 3.2, which is what macOS ships, treats "${arr[@]}" on an empty array
  # as unset under `set -u`. Nothing was started if it is empty, so there is
  # nothing to report either way.
  (( ${#STARTED_PORTS[@]} == 0 )) && return 0
  for port in "${STARTED_PORTS[@]}"; do
    if port_in_use "$port"; then
      warn "port $port is still bound after shutdown"
      held=1
    fi
  done
  (( held )) && warn "run: lsof -nP -iTCP:$API_PORT -sTCP:LISTEN   to find the process"
  return 0
}

# Prefix each line of a child's output so two servers in one terminal stay
# readable.
#
# `set -m` enables job control, which makes each background job a process-group
# leader. That is what lets shutdown signal the whole tree — `go run` spawns a
# separate compiled binary that would otherwise survive and keep holding the
# port. (setsid would be the obvious tool but does not exist on macOS.)
#
# Output goes through process substitution rather than a pipeline so that $!
# is the server's own PID, not sed's.
run_prefixed() {
  local label="$1" colour="$2"; shift 2
  set -m
  "$@" > >(sed -u "s/^/${colour}[${label}]${C_RESET} /") 2>&1 &
  PIDS+=("$!")
  set +m
}

start_backend() {
  export GOBPM_HTTP_ADDRESS=":${API_PORT}"
  export GOBPM_GRPC_ADDRESS=":${GRPC_PORT}"
  info "Backend  → http://localhost:${API_PORT}  (gRPC :${GRPC_PORT})"
  if command -v air >/dev/null 2>&1; then
    ok "air detected — backend will hot-reload on save"
    run_prefixed "api" "$C_GREEN" air
  else
    printf '%s       install air for backend hot reload: go install github.com/air-verse/air@latest%s\n' "$C_DIM" "$C_RESET"
    run_prefixed "api" "$C_GREEN" go run ./cmd/gobpm
  fi
}

# Fill a fresh installation with something to look at.
#
# Runs alongside the servers rather than before them: it waits for the backend
# to answer, and until it does there is nothing to seed. Its output is prefixed
# like theirs so it is clear which lines came from where.
start_sample() {
  run_prefixed "seed" "$C_YELLOW" "$ROOT/scripts/seed-sample.sh"
}

start_ui() {
  # Tells the Vite proxy where the backend actually is, so a non-default
  # API_PORT still works end to end.
  export GOBPM_BACKEND="http://localhost:${API_PORT}"
  [[ -d ui/node_modules ]] || { info "Installing UI dependencies"; (cd ui && bun install); }
  info "UI       → http://localhost:${UI_PORT}"
  # `bun --cwd` is not accepted by all bun versions, so cd in a subshell and
  # exec so the process group leader is vite itself.
  run_prefixed "ui" "$C_BLUE" bash -c 'cd ui && exec bun run dev -- --port "$1" --strictPort' _ "$UI_PORT"
}

# --- main ------------------------------------------------------------------

main() {
  local target="all" reset=0 sample=0 arg
  for arg in "$@"; do
    case "$arg" in
      backend|api) target="backend" ;;
      ui|front|frontend) target="ui" ;;
      all) target="all" ;;
      --reset) reset=1 ;;
      --sample|--samples|--seed) sample=1 ;;
      -h|--help) sed -n '2,13p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
      *) die "unknown argument: $arg (try --help)" ;;
    esac
  done

  check_prerequisites
  ensure_dev_env
  load_dev_env


  # Checked before the trap is installed, and before anything destructive:
  # nothing has been started yet, so a conflict here should say so and stop
  # rather than print a shutdown. --reset used to run first, so a port conflict
  # left you with the database deleted and no server to show for it.
  case "$target" in
    backend) check_ports "$API_PORT" "$GRPC_PORT" ;;
    ui)      check_ports "$UI_PORT" ;;
    all)     check_ports "$API_PORT" "$GRPC_PORT" "$UI_PORT" ;;
  esac

  if (( reset )); then
    if [[ -f "$DB_FILE" ]]; then
      info "Removing $DB_FILE"
      rm -f "$DB_FILE"
    fi
    # config.yaml pins the database and secrets chosen during first-time
    # setup; leaving it behind would send the server at the deleted database.
    rm -f "$ROOT/config.yaml"
    ok "reset — the setup wizard will run again"
  fi

  trap shutdown INT TERM HUP EXIT

  case "$target" in
    backend) STARTED_PORTS=("$API_PORT" "$GRPC_PORT")
             start_backend
             (( sample )) && start_sample
             ;;
    ui)      STARTED_PORTS=("$UI_PORT");               start_ui ;;
    all)     STARTED_PORTS=("$API_PORT" "$GRPC_PORT" "$UI_PORT")
             start_backend
             (( sample )) && start_sample
             start_ui
             printf '\n'
             ok "Open ${C_BOLD}http://localhost:${UI_PORT}${C_RESET} — first run shows the setup wizard"
             printf '%s     Ctrl-C stops both.%s\n\n' "$C_DIM" "$C_RESET"
             ;;
  esac

  wait
}

main "$@"
