// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/definition.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_definition_proto protoreflect.FileDescriptor

const file_services_definition_proto_rawDesc = "" +
	"\n" +
	"\x19services/definition.proto\x12\aprocess\x1a!endpoints/create_definition.proto\x1a endpoints/list_definitions.proto\x1a\x1eendpoints/get_definition.proto\x1a!endpoints/delete_definition.proto2\xf3\x02\n" +
	"\x11DefinitionService\x12Y\n" +
	"\x10CreateDefinition\x12 .process.CreateDefinitionRequest\x1a!.process.CreateDefinitionResponse\"\x00\x12V\n" +
	"\x0fListDefinitions\x12\x1f.process.ListDefinitionsRequest\x1a .process.ListDefinitionsResponse\"\x00\x12P\n" +
	"\rGetDefinition\x12\x1d.process.GetDefinitionRequest\x1a\x1e.process.GetDefinitionResponse\"\x00\x12Y\n" +
	"\x10DeleteDefinition\x12 .process.DeleteDefinitionRequest\x1a!.process.DeleteDefinitionResponse\"\x00B\x91\x01\n" +
	"\vcom.processB\x0fDefinitionProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_definition_proto_goTypes = []any{
	(*endpoints.CreateDefinitionRequest)(nil),  // 0: process.CreateDefinitionRequest
	(*endpoints.ListDefinitionsRequest)(nil),   // 1: process.ListDefinitionsRequest
	(*endpoints.GetDefinitionRequest)(nil),     // 2: process.GetDefinitionRequest
	(*endpoints.DeleteDefinitionRequest)(nil),  // 3: process.DeleteDefinitionRequest
	(*endpoints.CreateDefinitionResponse)(nil), // 4: process.CreateDefinitionResponse
	(*endpoints.ListDefinitionsResponse)(nil),  // 5: process.ListDefinitionsResponse
	(*endpoints.GetDefinitionResponse)(nil),    // 6: process.GetDefinitionResponse
	(*endpoints.DeleteDefinitionResponse)(nil), // 7: process.DeleteDefinitionResponse
}
var file_services_definition_proto_depIdxs = []int32{
	0, // 0: process.DefinitionService.CreateDefinition:input_type -> process.CreateDefinitionRequest
	1, // 1: process.DefinitionService.ListDefinitions:input_type -> process.ListDefinitionsRequest
	2, // 2: process.DefinitionService.GetDefinition:input_type -> process.GetDefinitionRequest
	3, // 3: process.DefinitionService.DeleteDefinition:input_type -> process.DeleteDefinitionRequest
	4, // 4: process.DefinitionService.CreateDefinition:output_type -> process.CreateDefinitionResponse
	5, // 5: process.DefinitionService.ListDefinitions:output_type -> process.ListDefinitionsResponse
	6, // 6: process.DefinitionService.GetDefinition:output_type -> process.GetDefinitionResponse
	7, // 7: process.DefinitionService.DeleteDefinition:output_type -> process.DeleteDefinitionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_definition_proto_init() }
func file_services_definition_proto_init() {
	if File_services_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_definition_proto_rawDesc), len(file_services_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_definition_proto_goTypes,
		DependencyIndexes: file_services_definition_proto_depIdxs,
	}.Build()
	File_services_definition_proto = out.File
	file_services_definition_proto_goTypes = nil
	file_services_definition_proto_depIdxs = nil
}
