// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/group.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_group_proto protoreflect.FileDescriptor

const file_services_group_proto_rawDesc = "" +
	"\n" +
	"\x14services/group.proto\x12\aprocess\x1a\x15endpoints/group.proto2\xac\x01\n" +
	"\fGroupService\x12G\n" +
	"\n" +
	"ListGroups\x12\x1a.process.ListGroupsRequest\x1a\x1b.process.ListGroupsResponse\"\x00\x12S\n" +
	"\x0eListUserGroups\x12\x1e.process.ListUserGroupsRequest\x1a\x1f.process.ListUserGroupsResponse\"\x00B\x8c\x01\n" +
	"\vcom.processB\n" +
	"GroupProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_group_proto_goTypes = []any{
	(*endpoints.ListGroupsRequest)(nil),      // 0: process.ListGroupsRequest
	(*endpoints.ListUserGroupsRequest)(nil),  // 1: process.ListUserGroupsRequest
	(*endpoints.ListGroupsResponse)(nil),     // 2: process.ListGroupsResponse
	(*endpoints.ListUserGroupsResponse)(nil), // 3: process.ListUserGroupsResponse
}
var file_services_group_proto_depIdxs = []int32{
	0, // 0: process.GroupService.ListGroups:input_type -> process.ListGroupsRequest
	1, // 1: process.GroupService.ListUserGroups:input_type -> process.ListUserGroupsRequest
	2, // 2: process.GroupService.ListGroups:output_type -> process.ListGroupsResponse
	3, // 3: process.GroupService.ListUserGroups:output_type -> process.ListUserGroupsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_group_proto_init() }
func file_services_group_proto_init() {
	if File_services_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_group_proto_rawDesc), len(file_services_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_group_proto_goTypes,
		DependencyIndexes: file_services_group_proto_depIdxs,
	}.Build()
	File_services_group_proto = out.File
	file_services_group_proto_goTypes = nil
	file_services_group_proto_depIdxs = nil
}
