// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/organization.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_organization_proto protoreflect.FileDescriptor

const file_services_organization_proto_rawDesc = "" +
	"\n" +
	"\x1bservices/organization.proto\x12\aprocess\x1a#endpoints/create_organization.proto\x1a endpoints/get_organization.proto\x1a\"endpoints/list_organizations.proto\x1a#endpoints/update_organization.proto\x1a#endpoints/delete_organization.proto2\xee\x03\n" +
	"\x13OrganizationService\x12_\n" +
	"\x12CreateOrganization\x12\".process.CreateOrganizationRequest\x1a#.process.CreateOrganizationResponse\"\x00\x12V\n" +
	"\x0fGetOrganization\x12\x1f.process.GetOrganizationRequest\x1a .process.GetOrganizationResponse\"\x00\x12\\\n" +
	"\x11ListOrganizations\x12!.process.ListOrganizationsRequest\x1a\".process.ListOrganizationsResponse\"\x00\x12_\n" +
	"\x12UpdateOrganization\x12\".process.UpdateOrganizationRequest\x1a#.process.UpdateOrganizationResponse\"\x00\x12_\n" +
	"\x12DeleteOrganization\x12\".process.DeleteOrganizationRequest\x1a#.process.DeleteOrganizationResponse\"\x00B\x93\x01\n" +
	"\vcom.processB\x11OrganizationProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_organization_proto_goTypes = []any{
	(*endpoints.CreateOrganizationRequest)(nil),  // 0: process.CreateOrganizationRequest
	(*endpoints.GetOrganizationRequest)(nil),     // 1: process.GetOrganizationRequest
	(*endpoints.ListOrganizationsRequest)(nil),   // 2: process.ListOrganizationsRequest
	(*endpoints.UpdateOrganizationRequest)(nil),  // 3: process.UpdateOrganizationRequest
	(*endpoints.DeleteOrganizationRequest)(nil),  // 4: process.DeleteOrganizationRequest
	(*endpoints.CreateOrganizationResponse)(nil), // 5: process.CreateOrganizationResponse
	(*endpoints.GetOrganizationResponse)(nil),    // 6: process.GetOrganizationResponse
	(*endpoints.ListOrganizationsResponse)(nil),  // 7: process.ListOrganizationsResponse
	(*endpoints.UpdateOrganizationResponse)(nil), // 8: process.UpdateOrganizationResponse
	(*endpoints.DeleteOrganizationResponse)(nil), // 9: process.DeleteOrganizationResponse
}
var file_services_organization_proto_depIdxs = []int32{
	0, // 0: process.OrganizationService.CreateOrganization:input_type -> process.CreateOrganizationRequest
	1, // 1: process.OrganizationService.GetOrganization:input_type -> process.GetOrganizationRequest
	2, // 2: process.OrganizationService.ListOrganizations:input_type -> process.ListOrganizationsRequest
	3, // 3: process.OrganizationService.UpdateOrganization:input_type -> process.UpdateOrganizationRequest
	4, // 4: process.OrganizationService.DeleteOrganization:input_type -> process.DeleteOrganizationRequest
	5, // 5: process.OrganizationService.CreateOrganization:output_type -> process.CreateOrganizationResponse
	6, // 6: process.OrganizationService.GetOrganization:output_type -> process.GetOrganizationResponse
	7, // 7: process.OrganizationService.ListOrganizations:output_type -> process.ListOrganizationsResponse
	8, // 8: process.OrganizationService.UpdateOrganization:output_type -> process.UpdateOrganizationResponse
	9, // 9: process.OrganizationService.DeleteOrganization:output_type -> process.DeleteOrganizationResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_organization_proto_init() }
func file_services_organization_proto_init() {
	if File_services_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_organization_proto_rawDesc), len(file_services_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_organization_proto_goTypes,
		DependencyIndexes: file_services_organization_proto_depIdxs,
	}.Build()
	File_services_organization_proto = out.File
	file_services_organization_proto_goTypes = nil
	file_services_organization_proto_depIdxs = nil
}
