// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/process.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_process_proto protoreflect.FileDescriptor

const file_services_process_proto_rawDesc = "" +
	"\n" +
	"\x16services/process.proto\x12\aprocess\x1a\x1dendpoints/start_process.proto\x1a\x1cendpoints/get_instance.proto\x1a\x1eendpoints/list_instances.proto\x1a\"endpoints/get_execution_path.proto2\xd8\x02\n" +
	"\x0eProcessService\x12M\n" +
	"\fStartProcess\x12\x1c.process.StartProcessRequest\x1a\x1d.process.StartProcessResponse\"\x00\x12J\n" +
	"\vGetInstance\x12\x1b.process.GetInstanceRequest\x1a\x1c.process.GetInstanceResponse\"\x00\x12P\n" +
	"\rListInstances\x12\x1d.process.ListInstancesRequest\x1a\x1e.process.ListInstancesResponse\"\x00\x12Y\n" +
	"\x10GetExecutionPath\x12 .process.GetExecutionPathRequest\x1a!.process.GetExecutionPathResponse\"\x00B\x8e\x01\n" +
	"\vcom.processB\fProcessProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_process_proto_goTypes = []any{
	(*endpoints.StartProcessRequest)(nil),      // 0: process.StartProcessRequest
	(*endpoints.GetInstanceRequest)(nil),       // 1: process.GetInstanceRequest
	(*endpoints.ListInstancesRequest)(nil),     // 2: process.ListInstancesRequest
	(*endpoints.GetExecutionPathRequest)(nil),  // 3: process.GetExecutionPathRequest
	(*endpoints.StartProcessResponse)(nil),     // 4: process.StartProcessResponse
	(*endpoints.GetInstanceResponse)(nil),      // 5: process.GetInstanceResponse
	(*endpoints.ListInstancesResponse)(nil),    // 6: process.ListInstancesResponse
	(*endpoints.GetExecutionPathResponse)(nil), // 7: process.GetExecutionPathResponse
}
var file_services_process_proto_depIdxs = []int32{
	0, // 0: process.ProcessService.StartProcess:input_type -> process.StartProcessRequest
	1, // 1: process.ProcessService.GetInstance:input_type -> process.GetInstanceRequest
	2, // 2: process.ProcessService.ListInstances:input_type -> process.ListInstancesRequest
	3, // 3: process.ProcessService.GetExecutionPath:input_type -> process.GetExecutionPathRequest
	4, // 4: process.ProcessService.StartProcess:output_type -> process.StartProcessResponse
	5, // 5: process.ProcessService.GetInstance:output_type -> process.GetInstanceResponse
	6, // 6: process.ProcessService.ListInstances:output_type -> process.ListInstancesResponse
	7, // 7: process.ProcessService.GetExecutionPath:output_type -> process.GetExecutionPathResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_process_proto_init() }
func file_services_process_proto_init() {
	if File_services_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_process_proto_rawDesc), len(file_services_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_process_proto_goTypes,
		DependencyIndexes: file_services_process_proto_depIdxs,
	}.Build()
	File_services_process_proto = out.File
	file_services_process_proto_goTypes = nil
	file_services_process_proto_depIdxs = nil
}
