// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/process.proto

package services

import (
	context "context"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessService_StartProcess_FullMethodName     = "/process.ProcessService/StartProcess"
	ProcessService_GetInstance_FullMethodName      = "/process.ProcessService/GetInstance"
	ProcessService_ListInstances_FullMethodName    = "/process.ProcessService/ListInstances"
	ProcessService_GetExecutionPath_FullMethodName = "/process.ProcessService/GetExecutionPath"
)

// ProcessServiceClient is the client API for ProcessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessServiceClient interface {
	StartProcess(ctx context.Context, in *endpoints.StartProcessRequest, opts ...grpc.CallOption) (*endpoints.StartProcessResponse, error)
	GetInstance(ctx context.Context, in *endpoints.GetInstanceRequest, opts ...grpc.CallOption) (*endpoints.GetInstanceResponse, error)
	ListInstances(ctx context.Context, in *endpoints.ListInstancesRequest, opts ...grpc.CallOption) (*endpoints.ListInstancesResponse, error)
	GetExecutionPath(ctx context.Context, in *endpoints.GetExecutionPathRequest, opts ...grpc.CallOption) (*endpoints.GetExecutionPathResponse, error)
}

type processServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessServiceClient(cc grpc.ClientConnInterface) ProcessServiceClient {
	return &processServiceClient{cc}
}

func (c *processServiceClient) StartProcess(ctx context.Context, in *endpoints.StartProcessRequest, opts ...grpc.CallOption) (*endpoints.StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.StartProcessResponse)
	err := c.cc.Invoke(ctx, ProcessService_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) GetInstance(ctx context.Context, in *endpoints.GetInstanceRequest, opts ...grpc.CallOption) (*endpoints.GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetInstanceResponse)
	err := c.cc.Invoke(ctx, ProcessService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) ListInstances(ctx context.Context, in *endpoints.ListInstancesRequest, opts ...grpc.CallOption) (*endpoints.ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ListInstancesResponse)
	err := c.cc.Invoke(ctx, ProcessService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) GetExecutionPath(ctx context.Context, in *endpoints.GetExecutionPathRequest, opts ...grpc.CallOption) (*endpoints.GetExecutionPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetExecutionPathResponse)
	err := c.cc.Invoke(ctx, ProcessService_GetExecutionPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessServiceServer is the server API for ProcessService service.
// All implementations must embed UnimplementedProcessServiceServer
// for forward compatibility.
type ProcessServiceServer interface {
	StartProcess(context.Context, *endpoints.StartProcessRequest) (*endpoints.StartProcessResponse, error)
	GetInstance(context.Context, *endpoints.GetInstanceRequest) (*endpoints.GetInstanceResponse, error)
	ListInstances(context.Context, *endpoints.ListInstancesRequest) (*endpoints.ListInstancesResponse, error)
	GetExecutionPath(context.Context, *endpoints.GetExecutionPathRequest) (*endpoints.GetExecutionPathResponse, error)
	mustEmbedUnimplementedProcessServiceServer()
}

// UnimplementedProcessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessServiceServer struct{}

func (UnimplementedProcessServiceServer) StartProcess(context.Context, *endpoints.StartProcessRequest) (*endpoints.StartProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedProcessServiceServer) GetInstance(context.Context, *endpoints.GetInstanceRequest) (*endpoints.GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedProcessServiceServer) ListInstances(context.Context, *endpoints.ListInstancesRequest) (*endpoints.ListInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedProcessServiceServer) GetExecutionPath(context.Context, *endpoints.GetExecutionPathRequest) (*endpoints.GetExecutionPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionPath not implemented")
}
func (UnimplementedProcessServiceServer) mustEmbedUnimplementedProcessServiceServer() {}
func (UnimplementedProcessServiceServer) testEmbeddedByValue()                        {}

// UnsafeProcessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessServiceServer will
// result in compilation errors.
type UnsafeProcessServiceServer interface {
	mustEmbedUnimplementedProcessServiceServer()
}

func RegisterProcessServiceServer(s grpc.ServiceRegistrar, srv ProcessServiceServer) {
	// If the following call pancis, it indicates UnimplementedProcessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessService_ServiceDesc, srv)
}

func _ProcessService_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).StartProcess(ctx, req.(*endpoints.StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).GetInstance(ctx, req.(*endpoints.GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).ListInstances(ctx, req.(*endpoints.ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_GetExecutionPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetExecutionPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).GetExecutionPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_GetExecutionPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).GetExecutionPath(ctx, req.(*endpoints.GetExecutionPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessService_ServiceDesc is the grpc.ServiceDesc for ProcessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "process.ProcessService",
	HandlerType: (*ProcessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcess",
			Handler:    _ProcessService_StartProcess_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _ProcessService_GetInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _ProcessService_ListInstances_Handler,
		},
		{
			MethodName: "GetExecutionPath",
			Handler:    _ProcessService_GetExecutionPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/process.proto",
}
