// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/project.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_project_proto protoreflect.FileDescriptor

const file_services_project_proto_rawDesc = "" +
	"\n" +
	"\x16services/project.proto\x12\aprocess\x1a\x1eendpoints/create_project.proto\x1a\x1bendpoints/get_project.proto\x1a\x1dendpoints/list_projects.proto\x1a\x1eendpoints/update_project.proto\x1a\x1eendpoints/delete_project.proto2\x9e\x03\n" +
	"\x0eProjectService\x12P\n" +
	"\rCreateProject\x12\x1d.process.CreateProjectRequest\x1a\x1e.process.CreateProjectResponse\"\x00\x12G\n" +
	"\n" +
	"GetProject\x12\x1a.process.GetProjectRequest\x1a\x1b.process.GetProjectResponse\"\x00\x12M\n" +
	"\fListProjects\x12\x1c.process.ListProjectsRequest\x1a\x1d.process.ListProjectsResponse\"\x00\x12P\n" +
	"\rUpdateProject\x12\x1d.process.UpdateProjectRequest\x1a\x1e.process.UpdateProjectResponse\"\x00\x12P\n" +
	"\rDeleteProject\x12\x1d.process.DeleteProjectRequest\x1a\x1e.process.DeleteProjectResponse\"\x00B\x8e\x01\n" +
	"\vcom.processB\fProjectProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_project_proto_goTypes = []any{
	(*endpoints.CreateProjectRequest)(nil),  // 0: process.CreateProjectRequest
	(*endpoints.GetProjectRequest)(nil),     // 1: process.GetProjectRequest
	(*endpoints.ListProjectsRequest)(nil),   // 2: process.ListProjectsRequest
	(*endpoints.UpdateProjectRequest)(nil),  // 3: process.UpdateProjectRequest
	(*endpoints.DeleteProjectRequest)(nil),  // 4: process.DeleteProjectRequest
	(*endpoints.CreateProjectResponse)(nil), // 5: process.CreateProjectResponse
	(*endpoints.GetProjectResponse)(nil),    // 6: process.GetProjectResponse
	(*endpoints.ListProjectsResponse)(nil),  // 7: process.ListProjectsResponse
	(*endpoints.UpdateProjectResponse)(nil), // 8: process.UpdateProjectResponse
	(*endpoints.DeleteProjectResponse)(nil), // 9: process.DeleteProjectResponse
}
var file_services_project_proto_depIdxs = []int32{
	0, // 0: process.ProjectService.CreateProject:input_type -> process.CreateProjectRequest
	1, // 1: process.ProjectService.GetProject:input_type -> process.GetProjectRequest
	2, // 2: process.ProjectService.ListProjects:input_type -> process.ListProjectsRequest
	3, // 3: process.ProjectService.UpdateProject:input_type -> process.UpdateProjectRequest
	4, // 4: process.ProjectService.DeleteProject:input_type -> process.DeleteProjectRequest
	5, // 5: process.ProjectService.CreateProject:output_type -> process.CreateProjectResponse
	6, // 6: process.ProjectService.GetProject:output_type -> process.GetProjectResponse
	7, // 7: process.ProjectService.ListProjects:output_type -> process.ListProjectsResponse
	8, // 8: process.ProjectService.UpdateProject:output_type -> process.UpdateProjectResponse
	9, // 9: process.ProjectService.DeleteProject:output_type -> process.DeleteProjectResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_project_proto_init() }
func file_services_project_proto_init() {
	if File_services_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_project_proto_rawDesc), len(file_services_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_project_proto_goTypes,
		DependencyIndexes: file_services_project_proto_depIdxs,
	}.Build()
	File_services_project_proto = out.File
	file_services_project_proto_goTypes = nil
	file_services_project_proto_depIdxs = nil
}
