syntax = "proto3";

package process;

import "endpoints/create_project.proto";
import "endpoints/get_project.proto";
import "endpoints/list_projects.proto";
import "endpoints/update_project.proto";
import "endpoints/delete_project.proto";

option go_package = "github.com/gsoultan/metis/api/proto/services;services";

service ProjectService { rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse) {} rpc GetProject(GetProjectRequest) returns (GetProjectResponse) {} rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse) {} rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse) {} rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse) {} }
