// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/signal.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_signal_proto protoreflect.FileDescriptor

const file_services_signal_proto_rawDesc = "" +
	"\n" +
	"\x15services/signal.proto\x12\aprocess\x1a endpoints/broadcast_signal.proto\x1a\x1cendpoints/send_message.proto2\xb3\x01\n" +
	"\rSignalService\x12V\n" +
	"\x0fBroadcastSignal\x12\x1f.process.BroadcastSignalRequest\x1a .process.BroadcastSignalResponse\"\x00\x12J\n" +
	"\vSendMessage\x12\x1b.process.SendMessageRequest\x1a\x1c.process.SendMessageResponse\"\x00B\x8d\x01\n" +
	"\vcom.processB\vSignalProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_signal_proto_goTypes = []any{
	(*endpoints.BroadcastSignalRequest)(nil),  // 0: process.BroadcastSignalRequest
	(*endpoints.SendMessageRequest)(nil),      // 1: process.SendMessageRequest
	(*endpoints.BroadcastSignalResponse)(nil), // 2: process.BroadcastSignalResponse
	(*endpoints.SendMessageResponse)(nil),     // 3: process.SendMessageResponse
}
var file_services_signal_proto_depIdxs = []int32{
	0, // 0: process.SignalService.BroadcastSignal:input_type -> process.BroadcastSignalRequest
	1, // 1: process.SignalService.SendMessage:input_type -> process.SendMessageRequest
	2, // 2: process.SignalService.BroadcastSignal:output_type -> process.BroadcastSignalResponse
	3, // 3: process.SignalService.SendMessage:output_type -> process.SendMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_signal_proto_init() }
func file_services_signal_proto_init() {
	if File_services_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_signal_proto_rawDesc), len(file_services_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_signal_proto_goTypes,
		DependencyIndexes: file_services_signal_proto_depIdxs,
	}.Build()
	File_services_signal_proto = out.File
	file_services_signal_proto_goTypes = nil
	file_services_signal_proto_depIdxs = nil
}
