// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/stats.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_stats_proto protoreflect.FileDescriptor

const file_services_stats_proto_rawDesc = "" +
	"\n" +
	"\x14services/stats.proto\x12\aprocess\x1a&endpoints/get_process_statistics.proto2u\n" +
	"\fStatsService\x12e\n" +
	"\x14GetProcessStatistics\x12$.process.GetProcessStatisticsRequest\x1a%.process.GetProcessStatisticsResponse\"\x00B\x8c\x01\n" +
	"\vcom.processB\n" +
	"StatsProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_stats_proto_goTypes = []any{
	(*endpoints.GetProcessStatisticsRequest)(nil),  // 0: process.GetProcessStatisticsRequest
	(*endpoints.GetProcessStatisticsResponse)(nil), // 1: process.GetProcessStatisticsResponse
}
var file_services_stats_proto_depIdxs = []int32{
	0, // 0: process.StatsService.GetProcessStatistics:input_type -> process.GetProcessStatisticsRequest
	1, // 1: process.StatsService.GetProcessStatistics:output_type -> process.GetProcessStatisticsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_stats_proto_init() }
func file_services_stats_proto_init() {
	if File_services_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_stats_proto_rawDesc), len(file_services_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_stats_proto_goTypes,
		DependencyIndexes: file_services_stats_proto_depIdxs,
	}.Build()
	File_services_stats_proto = out.File
	file_services_stats_proto_goTypes = nil
	file_services_stats_proto_depIdxs = nil
}
