// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/task.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_task_proto protoreflect.FileDescriptor

const file_services_task_proto_rawDesc = "" +
	"\n" +
	"\x13services/task.proto\x12\aprocess\x1a\x18endpoints/get_task.proto\x1a\x1aendpoints/list_tasks.proto\x1a\x1dendpoints/complete_task.proto\x1a\x1aendpoints/claim_task.proto\x1a\x1cendpoints/unclaim_task.proto\x1a&endpoints/list_tasks_by_assignee.proto\x1a(endpoints/list_tasks_by_candidates.proto2\xac\x04\n" +
	"\vTaskService\x12>\n" +
	"\aGetTask\x12\x17.process.GetTaskRequest\x1a\x18.process.GetTaskResponse\"\x00\x12D\n" +
	"\tListTasks\x12\x19.process.ListTasksRequest\x1a\x1a.process.ListTasksResponse\"\x00\x12M\n" +
	"\fCompleteTask\x12\x1c.process.CompleteTaskRequest\x1a\x1d.process.CompleteTaskResponse\"\x00\x12D\n" +
	"\tClaimTask\x12\x19.process.ClaimTaskRequest\x1a\x1a.process.ClaimTaskResponse\"\x00\x12J\n" +
	"\vUnclaimTask\x12\x1b.process.UnclaimTaskRequest\x1a\x1c.process.UnclaimTaskResponse\"\x00\x12X\n" +
	"\x13ListTasksByAssignee\x12#.process.ListTasksByAssigneeRequest\x1a\x1a.process.ListTasksResponse\"\x00\x12\\\n" +
	"\x15ListTasksByCandidates\x12%.process.ListTasksByCandidatesRequest\x1a\x1a.process.ListTasksResponse\"\x00B\x8b\x01\n" +
	"\vcom.processB\tTaskProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_task_proto_goTypes = []any{
	(*endpoints.GetTaskRequest)(nil),               // 0: process.GetTaskRequest
	(*endpoints.ListTasksRequest)(nil),             // 1: process.ListTasksRequest
	(*endpoints.CompleteTaskRequest)(nil),          // 2: process.CompleteTaskRequest
	(*endpoints.ClaimTaskRequest)(nil),             // 3: process.ClaimTaskRequest
	(*endpoints.UnclaimTaskRequest)(nil),           // 4: process.UnclaimTaskRequest
	(*endpoints.ListTasksByAssigneeRequest)(nil),   // 5: process.ListTasksByAssigneeRequest
	(*endpoints.ListTasksByCandidatesRequest)(nil), // 6: process.ListTasksByCandidatesRequest
	(*endpoints.GetTaskResponse)(nil),              // 7: process.GetTaskResponse
	(*endpoints.ListTasksResponse)(nil),            // 8: process.ListTasksResponse
	(*endpoints.CompleteTaskResponse)(nil),         // 9: process.CompleteTaskResponse
	(*endpoints.ClaimTaskResponse)(nil),            // 10: process.ClaimTaskResponse
	(*endpoints.UnclaimTaskResponse)(nil),          // 11: process.UnclaimTaskResponse
}
var file_services_task_proto_depIdxs = []int32{
	0,  // 0: process.TaskService.GetTask:input_type -> process.GetTaskRequest
	1,  // 1: process.TaskService.ListTasks:input_type -> process.ListTasksRequest
	2,  // 2: process.TaskService.CompleteTask:input_type -> process.CompleteTaskRequest
	3,  // 3: process.TaskService.ClaimTask:input_type -> process.ClaimTaskRequest
	4,  // 4: process.TaskService.UnclaimTask:input_type -> process.UnclaimTaskRequest
	5,  // 5: process.TaskService.ListTasksByAssignee:input_type -> process.ListTasksByAssigneeRequest
	6,  // 6: process.TaskService.ListTasksByCandidates:input_type -> process.ListTasksByCandidatesRequest
	7,  // 7: process.TaskService.GetTask:output_type -> process.GetTaskResponse
	8,  // 8: process.TaskService.ListTasks:output_type -> process.ListTasksResponse
	9,  // 9: process.TaskService.CompleteTask:output_type -> process.CompleteTaskResponse
	10, // 10: process.TaskService.ClaimTask:output_type -> process.ClaimTaskResponse
	11, // 11: process.TaskService.UnclaimTask:output_type -> process.UnclaimTaskResponse
	8,  // 12: process.TaskService.ListTasksByAssignee:output_type -> process.ListTasksResponse
	8,  // 13: process.TaskService.ListTasksByCandidates:output_type -> process.ListTasksResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_task_proto_init() }
func file_services_task_proto_init() {
	if File_services_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_task_proto_rawDesc), len(file_services_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_task_proto_goTypes,
		DependencyIndexes: file_services_task_proto_depIdxs,
	}.Build()
	File_services_task_proto = out.File
	file_services_task_proto_goTypes = nil
	file_services_task_proto_depIdxs = nil
}
