// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/task.proto

package services

import (
	context "context"
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_GetTask_FullMethodName               = "/process.TaskService/GetTask"
	TaskService_ListTasks_FullMethodName             = "/process.TaskService/ListTasks"
	TaskService_CompleteTask_FullMethodName          = "/process.TaskService/CompleteTask"
	TaskService_ClaimTask_FullMethodName             = "/process.TaskService/ClaimTask"
	TaskService_UnclaimTask_FullMethodName           = "/process.TaskService/UnclaimTask"
	TaskService_ListTasksByAssignee_FullMethodName   = "/process.TaskService/ListTasksByAssignee"
	TaskService_ListTasksByCandidates_FullMethodName = "/process.TaskService/ListTasksByCandidates"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetTask(ctx context.Context, in *endpoints.GetTaskRequest, opts ...grpc.CallOption) (*endpoints.GetTaskResponse, error)
	ListTasks(ctx context.Context, in *endpoints.ListTasksRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error)
	CompleteTask(ctx context.Context, in *endpoints.CompleteTaskRequest, opts ...grpc.CallOption) (*endpoints.CompleteTaskResponse, error)
	ClaimTask(ctx context.Context, in *endpoints.ClaimTaskRequest, opts ...grpc.CallOption) (*endpoints.ClaimTaskResponse, error)
	UnclaimTask(ctx context.Context, in *endpoints.UnclaimTaskRequest, opts ...grpc.CallOption) (*endpoints.UnclaimTaskResponse, error)
	ListTasksByAssignee(ctx context.Context, in *endpoints.ListTasksByAssigneeRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error)
	ListTasksByCandidates(ctx context.Context, in *endpoints.ListTasksByCandidatesRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *endpoints.GetTaskRequest, opts ...grpc.CallOption) (*endpoints.GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *endpoints.ListTasksRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CompleteTask(ctx context.Context, in *endpoints.CompleteTaskRequest, opts ...grpc.CallOption) (*endpoints.CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ClaimTask(ctx context.Context, in *endpoints.ClaimTaskRequest, opts ...grpc.CallOption) (*endpoints.ClaimTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ClaimTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UnclaimTask(ctx context.Context, in *endpoints.UnclaimTaskRequest, opts ...grpc.CallOption) (*endpoints.UnclaimTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.UnclaimTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_UnclaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasksByAssignee(ctx context.Context, in *endpoints.ListTasksByAssigneeRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasksByAssignee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasksByCandidates(ctx context.Context, in *endpoints.ListTasksByCandidatesRequest, opts ...grpc.CallOption) (*endpoints.ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasksByCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	GetTask(context.Context, *endpoints.GetTaskRequest) (*endpoints.GetTaskResponse, error)
	ListTasks(context.Context, *endpoints.ListTasksRequest) (*endpoints.ListTasksResponse, error)
	CompleteTask(context.Context, *endpoints.CompleteTaskRequest) (*endpoints.CompleteTaskResponse, error)
	ClaimTask(context.Context, *endpoints.ClaimTaskRequest) (*endpoints.ClaimTaskResponse, error)
	UnclaimTask(context.Context, *endpoints.UnclaimTaskRequest) (*endpoints.UnclaimTaskResponse, error)
	ListTasksByAssignee(context.Context, *endpoints.ListTasksByAssigneeRequest) (*endpoints.ListTasksResponse, error)
	ListTasksByCandidates(context.Context, *endpoints.ListTasksByCandidatesRequest) (*endpoints.ListTasksResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) GetTask(context.Context, *endpoints.GetTaskRequest) (*endpoints.GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasks(context.Context, *endpoints.ListTasksRequest) (*endpoints.ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) CompleteTask(context.Context, *endpoints.CompleteTaskRequest) (*endpoints.CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedTaskServiceServer) ClaimTask(context.Context, *endpoints.ClaimTaskRequest) (*endpoints.ClaimTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedTaskServiceServer) UnclaimTask(context.Context, *endpoints.UnclaimTaskRequest) (*endpoints.UnclaimTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnclaimTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasksByAssignee(context.Context, *endpoints.ListTasksByAssigneeRequest) (*endpoints.ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasksByAssignee not implemented")
}
func (UnimplementedTaskServiceServer) ListTasksByCandidates(context.Context, *endpoints.ListTasksByCandidatesRequest) (*endpoints.ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasksByCandidates not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*endpoints.GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*endpoints.ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CompleteTask(ctx, req.(*endpoints.CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ClaimTask(ctx, req.(*endpoints.ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UnclaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.UnclaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UnclaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UnclaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UnclaimTask(ctx, req.(*endpoints.UnclaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasksByAssignee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ListTasksByAssigneeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasksByAssignee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasksByAssignee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasksByAssignee(ctx, req.(*endpoints.ListTasksByAssigneeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasksByCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ListTasksByCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasksByCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasksByCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasksByCandidates(ctx, req.(*endpoints.ListTasksByCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "process.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _TaskService_CompleteTask_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _TaskService_ClaimTask_Handler,
		},
		{
			MethodName: "UnclaimTask",
			Handler:    _TaskService_UnclaimTask_Handler,
		},
		{
			MethodName: "ListTasksByAssignee",
			Handler:    _TaskService_ListTasksByAssignee_Handler,
		},
		{
			MethodName: "ListTasksByCandidates",
			Handler:    _TaskService_ListTasksByCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/task.proto",
}
