// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/user.proto

package services

import (
	endpoints "github.com/gsoultan/metis/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_user_proto protoreflect.FileDescriptor

const file_services_user_proto_rawDesc = "" +
	"\n" +
	"\x13services/user.proto\x12\aprocess\x1a\x14endpoints/user.proto2\x93\x01\n" +
	"\vUserService\x12>\n" +
	"\aGetUser\x12\x17.process.GetUserRequest\x1a\x18.process.GetUserResponse\"\x00\x12D\n" +
	"\tListUsers\x12\x19.process.ListUsersRequest\x1a\x1a.process.ListUsersResponse\"\x00B\x8b\x01\n" +
	"\vcom.processB\tUserProtoP\x01Z5github.com/gsoultan/metis/api/proto/services;services\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var file_services_user_proto_goTypes = []any{
	(*endpoints.GetUserRequest)(nil),    // 0: process.GetUserRequest
	(*endpoints.ListUsersRequest)(nil),  // 1: process.ListUsersRequest
	(*endpoints.GetUserResponse)(nil),   // 2: process.GetUserResponse
	(*endpoints.ListUsersResponse)(nil), // 3: process.ListUsersResponse
}
var file_services_user_proto_depIdxs = []int32{
	0, // 0: process.UserService.GetUser:input_type -> process.GetUserRequest
	1, // 1: process.UserService.ListUsers:input_type -> process.ListUsersRequest
	2, // 2: process.UserService.GetUser:output_type -> process.GetUserResponse
	3, // 3: process.UserService.ListUsers:output_type -> process.ListUsersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_user_proto_init() }
func file_services_user_proto_init() {
	if File_services_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_proto_rawDesc), len(file_services_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_proto_goTypes,
		DependencyIndexes: file_services_user_proto_depIdxs,
	}.Build()
	File_services_user_proto = out.File
	file_services_user_proto_goTypes = nil
	file_services_user_proto_depIdxs = nil
}
